glyph = [
    { character = 32, x = 0, y = 0, w = 0, h = 0, shift = 10, offset = 0 }, # space
    { character = 97, x = 0, y = 0, w = 24, h = 28, shift = 25, offset = 0 }, # a
    { character = 98, x = 25, y = 0, w = 28, h = 28, shift = 29, offset = 0 }, # b
    { character = 99, x = 54, y = 0, w = 28, h = 28, shift = 29, offset = 0 }, # c
    { character = 100, x = 83, y = 0, w = 26, h = 28, shift = 27, offset = 0 }, # d
    { character = 101, x = 110, y = 0, w = 25, h = 28, shift = 26, offset = 0 }, # e
    { character = 102, x = 136, y = 0, w = 25, h = 28, shift = 26, offset = 0 }, # f
    { character = 103, x = 162, y = 0, w = 27, h = 28, shift = 28, offset = 0 }, # g
    { character = 104, x = 190, y = 0, w = 26, h = 28, shift = 27, offset = 0 }, # h
    { character = 105, x = 217, y = 0, w = 12, h = 28, shift = 13, offset = 0 }, # i
    { character = 106, x = 230, y = 0, w = 29, h = 28, shift = 30, offset = 0 }, # j
    { character = 107, x = 260, y = 0, w = 28, h = 28, shift = 29, offset = 0 }, # k
    { character = 108, x = 289, y = 0, w = 22, h = 28, shift = 23, offset = 0 }, # l
    { character = 109, x = 312, y = 0, w = 39, h = 28, shift = 40, offset = 0 }, # m
    { character = 110, x = 352, y = 0, w = 27, h = 28, shift = 28, offset = 0 }, # n
    { character = 111, x = 380, y = 0, w = 27, h = 28, shift = 28, offset = 0 }, # o
    { character = 112, x = 408, y = 0, w = 28, h = 28, shift = 29, offset = 0 }, # p
    { character = 113, x = 437, y = 0, w = 27, h = 28, shift = 28, offset = 0 }, # q
    { character = 114, x = 465, y = 0, w = 28, h = 28, shift = 29, offset = 0 }, # r
    { character = 115, x = 494, y = 0, w = 31, h = 28, shift = 32, offset = 0 }, # s
    { character = 116, x = 526, y = 0, w = 28, h = 28, shift = 29, offset = 0 }, # t
    { character = 117, x = 555, y = 0, w = 26, h = 28, shift = 27, offset = 0 }, # u
    { character = 118, x = 582, y = 0, w = 26, h = 28, shift = 27, offset = 0 }, # v
    { character = 119, x = 609, y = 0, w = 28, h = 28, shift = 29, offset = 0 }, # w
    { character = 120, x = 638, y = 0, w = 31, h = 28, shift = 32, offset = 0 }, # x
    { character = 121, x = 670, y = 0, w = 28, h = 28, shift = 29, offset = 0 }, # y
    { character = 122, x = 699, y = 0, w = 29, h = 28, shift = 30, offset = 0 }, # z
    { character = 945, x = 0, y = 29, w = 24, h = 28, shift = 25, offset = 0 }, # α
    { character = 946, x = 25, y = 29, w = 28, h = 28, shift = 29, offset = 0 }, # β
    { character = 947, x = 54, y = 29, w = 22, h = 28, shift = 23, offset = 0 }, # γ
    { character = 948, x = 77, y = 29, w = 28, h = 28, shift = 29, offset = 0 }, # δ
    { character = 949, x = 106, y = 29, w = 25, h = 28, shift = 26, offset = 0 }, # ε
    { character = 950, x = 132, y = 29, w = 29, h = 28, shift = 30, offset = 0 }, # ζ
    { character = 951, x = 162, y = 29, w = 26, h = 28, shift = 27, offset = 0 }, # η
    { character = 952, x = 189, y = 29, w = 28, h = 28, shift = 29, offset = 0 }, # θ
    { character = 953, x = 218, y = 29, w = 12, h = 28, shift = 13, offset = 0 }, # ι
    { character = 954, x = 231, y = 29, w = 28, h = 28, shift = 29, offset = 0 }, # κ
    { character = 955, x = 260, y = 29, w = 34, h = 28, shift = 35, offset = 0 }, # λ
    { character = 956, x = 295, y = 29, w = 39, h = 28, shift = 40, offset = 0 }, # μ
    { character = 957, x = 335, y = 29, w = 27, h = 28, shift = 28, offset = 0 }, # ν
    { character = 958, x = 363, y = 29, w = 29, h = 28, shift = 30, offset = 0 }, # ξ
    { character = 959, x = 393, y = 29, w = 27, h = 28, shift = 28, offset = 0 }, # ο
    { character = 960, x = 421, y = 29, w = 27, h = 28, shift = 28, offset = 0 }, # π
    { character = 961, x = 449, y = 29, w = 28, h = 28, shift = 29, offset = 0 }, # ρ
    { character = 963, x = 478, y = 29, w = 27, h = 28, shift = 28, offset = 0 }, # σ
    { character = 964, x = 506, y = 29, w = 28, h = 28, shift = 29, offset = 0 }, # τ
    { character = 965, x = 535, y = 29, w = 28, h = 28, shift = 29, offset = 0 }, # υ
    { character = 966, x = 564, y = 29, w = 30, h = 28, shift = 31, offset = 0 }, # φ
    { character = 967, x = 595, y = 29, w = 31, h = 28, shift = 32, offset = 0 }, # χ
    { character = 968, x = 627, y = 29, w = 26, h = 28, shift = 27, offset = 0 }, # ψ
    { character = 969, x = 654, y = 29, w = 31, h = 28, shift = 32, offset = 0 }, # ω
    { character = 1072, x = 0, y = 58, w = 24, h = 28, shift = 25, offset = 0 }, # а
    { character = 1073, x = 25, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # б
    { character = 1074, x = 54, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # в
    { character = 1075, x = 83, y = 58, w = 22, h = 28, shift = 23, offset = 0 }, # г
    { character = 1076, x = 106, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # д
    { character = 1077, x = 135, y = 58, w = 25, h = 28, shift = 26, offset = 0 }, # е
    { character = 1078, x = 161, y = 58, w = 30, h = 28, shift = 31, offset = 0 }, # ж
    { character = 1079, x = 192, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # з
    { character = 1080, x = 221, y = 58, w = 27, h = 28, shift = 28, offset = 0 }, # и
    { character = 1081, x = 249, y = 58, w = 27, h = 28, shift = 28, offset = 0 }, # й
    { character = 1082, x = 277, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # к
    { character = 1083, x = 306, y = 58, w = 34, h = 28, shift = 35, offset = 0 }, # л
    { character = 1084, x = 341, y = 58, w = 39, h = 28, shift = 40, offset = 0 }, # м
    { character = 1085, x = 381, y = 58, w = 26, h = 28, shift = 27, offset = 0 }, # н
    { character = 1086, x = 408, y = 58, w = 27, h = 28, shift = 28, offset = 0 }, # о
    { character = 1087, x = 436, y = 58, w = 27, h = 28, shift = 28, offset = 0 }, # п
    { character = 1088, x = 464, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # р
    { character = 1089, x = 493, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # с
    { character = 1090, x = 522, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # т
    { character = 1091, x = 551, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # у
    { character = 1092, x = 580, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # ф
    { character = 1093, x = 609, y = 58, w = 31, h = 28, shift = 32, offset = 0 }, # х
    { character = 1094, x = 641, y = 58, w = 26, h = 28, shift = 27, offset = 0 }, # ц
    { character = 1095, x = 668, y = 58, w = 26, h = 28, shift = 27, offset = 0 }, # ч
    { character = 1096, x = 695, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # ш
    { character = 1097, x = 724, y = 58, w = 32, h = 28, shift = 33, offset = 0 }, # щ
    { character = 1098, x = 757, y = 58, w = 34, h = 28, shift = 35, offset = 0 }, # ъ
    { character = 1099, x = 792, y = 58, w = 31, h = 28, shift = 32, offset = 0 }, # ы
    { character = 1100, x = 824, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # ь
    { character = 1101, x = 853, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # э
    { character = 1102, x = 882, y = 58, w = 37, h = 28, shift = 38, offset = 0 }, # ю
    { character = 1103, x = 920, y = 58, w = 28, h = 28, shift = 29, offset = 0 }, # я
    { character = 48, x = 0, y = 87, w = 29, h = 28, shift = 30, offset = 0 }, # 0
    { character = 49, x = 30, y = 87, w = 17, h = 28, shift = 18, offset = 0 }, # 1
    { character = 50, x = 48, y = 87, w = 23, h = 28, shift = 24, offset = 0 }, # 2
    { character = 51, x = 72, y = 87, w = 24, h = 28, shift = 25, offset = 0 }, # 3
    { character = 52, x = 97, y = 87, w = 26, h = 28, shift = 27, offset = 0 }, # 4
    { character = 53, x = 124, y = 87, w = 24, h = 28, shift = 25, offset = 0 }, # 5
    { character = 54, x = 149, y = 87, w = 24, h = 28, shift = 25, offset = 0 }, # 6
    { character = 55, x = 174, y = 87, w = 21, h = 28, shift = 22, offset = 0 }, # 7
    { character = 56, x = 196, y = 87, w = 22, h = 28, shift = 23, offset = 0 }, # 8
    { character = 57, x = 219, y = 87, w = 24, h = 28, shift = 25, offset = 0 }, # 9
    { character = 46, x = 0, y = 116, w = 9, h = 28, shift = 10, offset = 0 }, # .
    { character = 44, x = 10, y = 116, w = 9, h = 28, shift = 10, offset = 0 }, # ,
    { character = 58, x = 20, y = 116, w = 9, h = 28, shift = 10, offset = 0 }, # :
    { character = 63, x = 30, y = 116, w = 27, h = 28, shift = 28, offset = 0 }, # ?
    { character = 33, x = 58, y = 116, w = 10, h = 28, shift = 11, offset = 0 }, # !
    { character = 40, x = 69, y = 116, w = 9, h = 28, shift = 10, offset = 0 }, # (
    { character = 41, x = 79, y = 116, w = 9, h = 28, shift = 10, offset = 0 }, # )
    { character = 47, x = 89, y = 116, w = 25, h = 28, shift = 26, offset = 0 }, # /
    { character = 37, x = 115, y = 116, w = 33, h = 28, shift = 34, offset = 0 }, # %
    { character = 39, x = 149, y = 116, w = 9, h = 28, shift = 10, offset = 0 }, # '
    { character = 59, x = 159, y = 116, w = 9, h = 28, shift = 10, offset = 0 }, # ;
    { character = 38, x = 169, y = 116, w = 29, h = 28, shift = 30, offset = 0 }, # &
    { character = 45, x = 199, y = 116, w = 19, h = 28, shift = 20, offset = 0 }, # -
    { character = 43, x = 219, y = 116, w = 17, h = 28, shift = 18, offset = 0 }, # +
    { character = 60, x = 237, y = 116, w = 15, h = 28, shift = 16, offset = 0 }, # <
    { character = 62, x = 253, y = 116, w = 15, h = 28, shift = 16, offset = 0 }, # >
    { character = 8595, x = 269, y = 116, w = 22, h = 28, shift = 23, offset = 0 }, # ↓
    { character = 8593, x = 292, y = 116, w = 22, h = 28, shift = 23, offset = 0 }, # ↑
    { character = 1169, x = 0, y = 145, w = 22, h = 28, shift = 23, offset = 0 }, # ґ
    { character = 1108, x = 23, y = 145, w = 28, h = 28, shift = 29, offset = 0 }, # є
    { character = 1111, x = 52, y = 145, w = 12, h = 28, shift = 13, offset = 0 }, # ї
]
