glyph = [
    { character = 32, x = 0, y = 0, w = 0, h = 0, shift = 6, offset = 0 }, # space
    { character = 97, x = 0, y = 0, w = 15, h = 15, shift = 16, offset = 0 }, # a
    { character = 98, x = 16, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # b
    { character = 99, x = 33, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # c
    { character = 100, x = 50, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # d
    { character = 101, x = 67, y = 0, w = 15, h = 15, shift = 16, offset = 0 }, # e
    { character = 102, x = 83, y = 0, w = 15, h = 15, shift = 16, offset = 0 }, # f
    { character = 103, x = 99, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # g
    { character = 104, x = 116, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # h
    { character = 105, x = 133, y = 0, w = 8, h = 15, shift = 9, offset = 0 }, # i
    { character = 106, x = 142, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # j
    { character = 107, x = 159, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # k
    { character = 108, x = 176, y = 0, w = 13, h = 15, shift = 14, offset = 0 }, # l
    { character = 109, x = 190, y = 0, w = 22, h = 15, shift = 23, offset = 0 }, # m
    { character = 110, x = 213, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # n
    { character = 111, x = 230, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # o
    { character = 112, x = 247, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # p
    { character = 113, x = 264, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # q
    { character = 114, x = 281, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # r
    { character = 115, x = 298, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # s
    { character = 116, x = 315, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # t
    { character = 117, x = 332, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # u
    { character = 118, x = 349, y = 0, w = 15, h = 15, shift = 16, offset = 0 }, # v
    { character = 119, x = 365, y = 0, w = 18, h = 15, shift = 19, offset = 0 }, # w
    { character = 120, x = 384, y = 0, w = 18, h = 15, shift = 19, offset = 0 }, # x
    { character = 121, x = 403, y = 0, w = 16, h = 15, shift = 17, offset = 0 }, # y
    { character = 122, x = 420, y = 0, w = 15, h = 15, shift = 16, offset = 0 }, # z
    { character = 945, x = 0, y = 16, w = 15, h = 15, shift = 16, offset = 0 }, # α
    { character = 946, x = 16, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # β
    { character = 947, x = 33, y = 16, w = 13, h = 15, shift = 14, offset = 0 }, # γ
    { character = 948, x = 47, y = 16, w = 15, h = 15, shift = 16, offset = 0 }, # δ
    { character = 949, x = 63, y = 16, w = 15, h = 15, shift = 16, offset = 0 }, # ε
    { character = 950, x = 79, y = 16, w = 15, h = 15, shift = 16, offset = 0 }, # ζ
    { character = 951, x = 95, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # η
    { character = 952, x = 112, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # θ
    { character = 953, x = 129, y = 16, w = 8, h = 15, shift = 9, offset = 0 }, # ι
    { character = 954, x = 138, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # κ
    { character = 955, x = 155, y = 16, w = 18, h = 15, shift = 19, offset = 0 }, # λ
    { character = 956, x = 174, y = 16, w = 22, h = 15, shift = 23, offset = 0 }, # μ
    { character = 957, x = 197, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # ν
    { character = 958, x = 214, y = 16, w = 15, h = 15, shift = 16, offset = 0 }, # ξ
    { character = 959, x = 230, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # ο
    { character = 960, x = 247, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # π
    { character = 961, x = 264, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # ρ
    { character = 963, x = 281, y = 16, w = 14, h = 15, shift = 15, offset = 0 }, # σ
    { character = 964, x = 296, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # τ
    { character = 965, x = 313, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # υ
    { character = 966, x = 330, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # φ
    { character = 967, x = 347, y = 16, w = 18, h = 15, shift = 19, offset = 0 }, # χ
    { character = 968, x = 366, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # ψ
    { character = 969, x = 383, y = 16, w = 16, h = 15, shift = 17, offset = 0 }, # ω
    { character = 1072, x = 0, y = 32, w = 15, h = 15, shift = 16, offset = 0 }, # а
    { character = 1073, x = 16, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # б
    { character = 1074, x = 33, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # в
    { character = 1075, x = 50, y = 32, w = 13, h = 15, shift = 14, offset = 0 }, # г
    { character = 1076, x = 64, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # д
    { character = 1077, x = 81, y = 32, w = 15, h = 15, shift = 16, offset = 0 }, # е
    { character = 1078, x = 97, y = 32, w = 18, h = 15, shift = 19, offset = 0 }, # ж
    { character = 1079, x = 116, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # з
    { character = 1080, x = 133, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # и
    { character = 1081, x = 150, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # й
    { character = 1082, x = 167, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # к
    { character = 1083, x = 184, y = 32, w = 18, h = 15, shift = 19, offset = 0 }, # л
    { character = 1084, x = 203, y = 32, w = 22, h = 15, shift = 23, offset = 0 }, # м
    { character = 1085, x = 226, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # н
    { character = 1086, x = 243, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # о
    { character = 1087, x = 260, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # п
    { character = 1088, x = 277, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # р
    { character = 1089, x = 294, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # с
    { character = 1090, x = 311, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # т
    { character = 1091, x = 328, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # у
    { character = 1092, x = 345, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # ф
    { character = 1093, x = 362, y = 32, w = 18, h = 15, shift = 19, offset = 0 }, # х
    { character = 1094, x = 381, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # ц
    { character = 1095, x = 398, y = 32, w = 15, h = 15, shift = 16, offset = 0 }, # ч
    { character = 1096, x = 414, y = 32, w = 18, h = 15, shift = 19, offset = 0 }, # ш
    { character = 1097, x = 433, y = 32, w = 20, h = 15, shift = 21, offset = 0 }, # щ
    { character = 1098, x = 454, y = 32, w = 19, h = 15, shift = 20, offset = 0 }, # ъ
    { character = 1099, x = 474, y = 32, w = 19, h = 15, shift = 20, offset = 0 }, # ы
    { character = 1100, x = 494, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # ь
    { character = 1101, x = 511, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # э
    { character = 1102, x = 528, y = 32, w = 21, h = 15, shift = 22, offset = 0 }, # ю
    { character = 1103, x = 550, y = 32, w = 16, h = 15, shift = 17, offset = 0 }, # я
    { character = 48, x = 0, y = 48, w = 17, h = 15, shift = 18, offset = 0 }, # 0
    { character = 49, x = 18, y = 48, w = 10, h = 15, shift = 11, offset = 0 }, # 1
    { character = 50, x = 29, y = 48, w = 15, h = 15, shift = 16, offset = 0 }, # 2
    { character = 51, x = 45, y = 48, w = 15, h = 15, shift = 16, offset = 0 }, # 3
    { character = 52, x = 61, y = 48, w = 15, h = 15, shift = 16, offset = 0 }, # 4
    { character = 53, x = 77, y = 48, w = 15, h = 15, shift = 16, offset = 0 }, # 5
    { character = 54, x = 93, y = 48, w = 14, h = 15, shift = 15, offset = 0 }, # 6
    { character = 55, x = 108, y = 48, w = 11, h = 15, shift = 12, offset = 0 }, # 7
    { character = 56, x = 120, y = 48, w = 12, h = 15, shift = 13, offset = 0 }, # 8
    { character = 57, x = 133, y = 48, w = 14, h = 15, shift = 15, offset = 0 }, # 9
    { character = 46, x = 0, y = 64, w = 5, h = 15, shift = 6, offset = 0 }, # .
    { character = 44, x = 6, y = 64, w = 5, h = 15, shift = 6, offset = 0 }, # ,
    { character = 58, x = 12, y = 64, w = 5, h = 15, shift = 6, offset = 0 }, # :
    { character = 63, x = 18, y = 64, w = 14, h = 15, shift = 15, offset = 0 }, # ?
    { character = 33, x = 33, y = 64, w = 6, h = 15, shift = 7, offset = 0 }, # !
    { character = 40, x = 40, y = 64, w = 6, h = 15, shift = 7, offset = 0 }, # (
    { character = 41, x = 47, y = 64, w = 6, h = 15, shift = 7, offset = 0 }, # )
    { character = 47, x = 54, y = 64, w = 13, h = 15, shift = 14, offset = 0 }, # /
    { character = 37, x = 68, y = 64, w = 17, h = 15, shift = 18, offset = 0 }, # %
    { character = 39, x = 86, y = 64, w = 5, h = 15, shift = 6, offset = 0 }, # '
    { character = 59, x = 92, y = 64, w = 5, h = 15, shift = 6, offset = 0 }, # ;
    { character = 38, x = 98, y = 64, w = 16, h = 15, shift = 17, offset = 0 }, # &
    { character = 45, x = 115, y = 64, w = 10, h = 15, shift = 11, offset = 0 }, # -
    { character = 43, x = 126, y = 64, w = 10, h = 15, shift = 11, offset = 0 }, # +
    { character = 60, x = 137, y = 64, w = 9, h = 15, shift = 10, offset = 0 }, # <
    { character = 62, x = 147, y = 64, w = 9, h = 15, shift = 10, offset = 0 }, # >
    { character = 8595, x = 157, y = 64, w = 12, h = 15, shift = 13, offset = 0 }, # ↓
    { character = 8593, x = 170, y = 64, w = 12, h = 15, shift = 13, offset = 0 }, # ↑
    { character = 1169, x = 0, y = 80, w = 13, h = 15, shift = 14, offset = 0 }, # ґ
    { character = 1108, x = 14, y = 80, w = 16, h = 15, shift = 17, offset = 0 }, # є
    { character = 1111, x = 31, y = 80, w = 8, h = 15, shift = 9, offset = 0 }, # ї
]
