achivement = { file = "achivement.mp3", volume = 255, audio-track = "player-sfx" }
acid = { file = "Objects/acid.mp3", volume = 255, audio-track = "player-sfx" }
act9 = { file = "Music/act9.mp3", volume = 77, audio-track = "music" }
act9_chase = { file = "Music/act9_chase.mp3", volume = 77, audio-track = "music" }
angelisland = { file = "Music/angelisland.mp3", volume = 51, audio-track = "music" }
angelisland_chase = { file = "Music/angelisland_chase.ogg", volume = 77, audio-track = "music" }
blackring = { file = "Objects/blackring.wav", volume = 255, audio-track = "player-sfx" }
blackring_ball = { file = "Objects/blackring_ball.mp3", volume = 255, audio-track = "player-sfx" }
bluespheres = { file = "Music/bluespheres.mp3", volume = 77, audio-track = "music" }
boohoo = { file = "Objects/boohoo.wav", volume = 255, audio-track = "player-sfx" }
boom = { file = "boom.mp3", volume = 255, audio-track = "player-sfx" }
bos = { file = "bos.mp3", volume = 178, audio-track = "player-sfx" }
break = { file = "Objects/break.wav", volume = 255, audio-track = "player-sfx" }
buble = { file = "Player/buble.wav", volume = 255, audio-track = "player-sfx" }
chaos_attack = { file = "Player/Chaos/chaos_attack.mp3", volume = 255, audio-track = "player-sfx" }
chaos_dash = { file = "Player/Chaos/chaos_dash.ogg", volume = 255, audio-track = "player-sfx" }
chaos_kill = { file = "Player/Chaos/chaos_kill.mp3", volume = 255, audio-track = "player-sfx" }
chaos_kill2 = { file = "Player/Chaos/chaos_kill2.mp3", volume = 255, audio-track = "player-sfx" }
chaos_kill3 = { file = "Player/Chaos/chaos_kill3.mp3", volume = 255, audio-track = "player-sfx" }
chaos_kill4 = { file = "Player/Chaos/chaos_kill4.mp3", volume = 255, audio-track = "player-sfx" }
chaos_kill5 = { file = "Player/Chaos/chaos_kill5.mp3", volume = 255, audio-track = "player-sfx" }
chaos_kill6 = { file = "Player/Chaos/chaos_kill6.mp3", volume = 255, audio-track = "player-sfx" }
chaos_kill7 = { file = "Player/Chaos/chaos_kill7.mp3", volume = 255, audio-track = "player-sfx" }
chaos_kill8 = { file = "Player/Chaos/chaos_kill8.mp3", volume = 255, audio-track = "player-sfx" }
chaos_land = { file = "Player/Chaos/chaos_land.mp3", volume = 245, audio-track = "player-sfx" }
chaos_laugh = { file = "Player/Chaos/chaos_laugh.mp3", volume = 255, audio-track = "player-sfx" }
chaos_pizza = { file = "Player/Chaos/chaos_pizza.wav", volume = 255, audio-track = "player-sfx" }
chaos_stun = { file = "Player/Chaos/chaos_stun.ogg", volume = 255, audio-track = "player-sfx" }
chaos_sturn = { file = "Player/Chaos/chaos_sturn.mp3", volume = 255, audio-track = "player-sfx" }
chaos_taunt = { file = "Player/Chaos/chaos_taunt.mp3", volume = 255, audio-track = "player-sfx" }
chaos_taunt2 = { file = "Player/Chaos/chaos_taunt2.mp3", volume = 255, audio-track = "player-sfx" }
chaos_vineboom = { file = "Player/Chaos/chaos_vineboom.wav", volume = 255, audio-track = "player-sfx" }
chase = { file = "Music/chase.ogg", volume = 255, audio-track = "music" }
clock = { file = "Menu/clock.wav", volume = 255, audio-track = "ui-sfx" }
creamdash = { file = "Player/Cream/creamdash.wav", volume = 255, audio-track = "player-sfx" }
creamring = { file = "Player/Cream/creamring.wav", volume = 255, audio-track = "player-sfx" }
darktower = { file = "Music/darktower.mp3", volume = 255, audio-track = "music" }
darktower_chase = { file = "Music/darktower_chase.mp3", volume = 178, audio-track = "music" }
dash = { file = "Player/dash.wav", volume = 255, audio-track = "player-sfx" }
dead = { file = "Player/dead.wav", volume = 255, audio-track = "player-sfx" }
demonization = { file = "Player/demonization.wav", volume = 255, audio-track = "player-sfx" }
deserttown = { file = "Music/deserttown.mp3", volume = 77, audio-track = "music" }
deserttown_chase = { file = "Music/deserttown_chase.mp3", volume = 77, audio-track = "music" }
destiny = { file = "Objects/destiny.wav", volume = 255, audio-track = "player-sfx" }
door = { file = "Objects/door.wav", volume = 255, audio-track = "player-sfx" }
dotdotdot = { file = "Music/dotdotdot.ogg", volume = 77, audio-track = "music" }
dotdotdot2 = { file = "Music/dotdotdot2.ogg", volume = 77, audio-track = "music" }
dotdotdot_chase = { file = "Music/dotdotdot_chase.mp3", volume = 77, audio-track = "music" }
dummy = { file = "Objects/dummy.wav", volume = 255, audio-track = "player-sfx" }
dummy2 = { file = "Objects/dummy2.wav", volume = 255, audio-track = "player-sfx" }
dummy3 = { file = "Objects/dummy3.wav", volume = 255, audio-track = "player-sfx" }
echain = { file = "Objects/echain.wav", volume = 178, audio-track = "player-sfx" }
echain_prepare = { file = "Objects/echain_prepare.wav", volume = 229, audio-track = "player-sfx" }
egg_djump = { file = "Player/Egg/egg_djump.ogg", volume = 255, audio-track = "player-sfx" }
egg_shield = { file = "Player/Egg/egg_shield.wav", volume = 255, audio-track = "player-sfx" }
egg_tracker = { file = "Player/Egg/egg_tracker.wav", volume = 255, audio-track = "player-sfx" }
egg_tracker_activate = { file = "Player/Egg/egg_tracker_activate.wav", volume = 255, audio-track = "player-sfx" }
electroshock = { file = "Effects/electroshock.wav", volume = 97, audio-track = "player-sfx" }
exe_appear = { file = "Player/Exe/exe_appear.wav", volume = 255, audio-track = "player-sfx" }
exe_appear2 = { file = "Player/Exe/exe_appear2.wav", volume = 255, audio-track = "player-sfx" }
exe_appear3 = { file = "Player/Exe/exe_appear3.wav", volume = 255, audio-track = "player-sfx" }
exe_invisenter = { file = "Player/Exe/exe_invisenter.mp3", volume = 255, audio-track = "player-sfx" }
exe_invisenter2 = { file = "Player/Exe/exe_invisenter2.mp3", volume = 255, audio-track = "player-sfx" }
exe_kill1 = { file = "Player/Exe/exe_kill1.wav", volume = 255, audio-track = "player-sfx" }
exe_kill2 = { file = "Player/Exe/exe_kill2.wav", volume = 255, audio-track = "player-sfx" }
exe_kill3 = { file = "Player/Exe/exe_kill3.wav", volume = 255, audio-track = "player-sfx" }
exe_kill4 = { file = "Player/Exe/exe_kill4.wav", volume = 255, audio-track = "player-sfx" }
exe_laugh = { file = "exe_laugh.wav", volume = 255, audio-track = "player-sfx" }
exe_ringshutter = { file = "Player/Exe/exe_ringshutter.wav", volume = 255, audio-track = "player-sfx" }
exe_stun = { file = "Player/Exe/exe_stun.wav", volume = 255, audio-track = "player-sfx" }
exe_stun2 = { file = "Player/Exe/exe_stun2.wav", volume = 255, audio-track = "player-sfx" }
exe_taunt = { file = "Player/Exe/exe_taunt.wav", volume = 255, audio-track = "player-sfx" }
exe_taunt1 = { file = "Player/Exe/exe_taunt1.wav", volume = 255, audio-track = "player-sfx" }
exe_taunt2 = { file = "Player/Exe/exe_taunt2.wav", volume = 255, audio-track = "player-sfx" }
exe_wins = { file = "Ambient/exe_wins.wav", volume = 255, audio-track = "ambient" }
exeller_clone = { file = "Player/Exeller/exeller_clone.wav", volume = 229, audio-track = "player-sfx" }
exeller_cloneline = { file = "Player/Exeller/exeller_cloneline.mp3", volume = 77, audio-track = "player-sfx" }
exeller_kill1 = { file = "Player/Exeller/exeller_kill1.mp3", volume = 77, audio-track = "player-sfx" }
exeller_kill2 = { file = "Player/Exeller/exeller_kill2.mp3", volume = 77, audio-track = "player-sfx" }
exeller_kill3 = { file = "Player/Exeller/exeller_kill3.mp3", volume = 77, audio-track = "player-sfx" }
exeller_kill4 = { file = "Player/Exeller/exeller_kill4.mp3", volume = 77, audio-track = "player-sfx" }
exeller_kill5 = { file = "Player/Exeller/exeller_kill5.mp3", volume = 77, audio-track = "player-sfx" }
exeller_kill6 = { file = "Player/Exeller/exeller_kill6.mp3", volume = 77, audio-track = "player-sfx" }
exeller_kill7 = { file = "Player/Exeller/exeller_kill7.mp3", volume = 77, audio-track = "player-sfx" }
exeller_laugh = { file = "Player/Exeller/exeller_laugh.mp3", volume = 178, audio-track = "player-sfx" }
exeller_stun = { file = "Player/Exeller/exeller_stun.mp3", volume = 77, audio-track = "player-sfx" }
exeller_taunt1 = { file = "Player/Exeller/exeller_taunt1.mp3", volume = 77, audio-track = "player-sfx" }
exeller_taunt2 = { file = "Player/Exeller/exeller_taunt2.mp3", volume = 77, audio-track = "player-sfx" }
exeller_taunt3 = { file = "Player/Exeller/exeller_taunt3.mp3", volume = 77, audio-track = "player-sfx" }
exetior_kill1 = { file = "Player/Exetior/exetior_kill1.wav", volume = 255, audio-track = "player-sfx" }
exetior_kill2 = { file = "Player/Exetior/exetior_kill2.wav", volume = 255, audio-track = "player-sfx" }
exetior_kill3 = { file = "Player/Exetior/exetior_kill3.wav", volume = 255, audio-track = "player-sfx" }
exetior_kill4 = { file = "Player/Exetior/exetior_kill4.wav", volume = 255, audio-track = "player-sfx" }
exetior_kill5 = { file = "Player/Exetior/exetior_kill5.wav", volume = 255, audio-track = "player-sfx" }
exetior_kill6 = { file = "Player/Exetior/exetior_kill6.wav", volume = 255, audio-track = "player-sfx" }
exetior_laugh = { file = "Player/Exetior/exetior_laugh.wav", volume = 255, audio-track = "player-sfx" }
exetior_ring1 = { file = "Player/Exetior/exetior_ring1.wav", volume = 255, audio-track = "player-sfx" }
exetior_ring2 = { file = "Player/Exetior/exetior_ring2.wav", volume = 255, audio-track = "player-sfx" }
exetior_ring3 = { file = "Player/Exetior/exetior_ring3.wav", volume = 255, audio-track = "player-sfx" }
exetior_ring4 = { file = "Player/Exetior/exetior_ring4.wav", volume = 255, audio-track = "player-sfx" }
exetior_shockwave = { file = "Player/Exetior/exetior_shockwave.mp3", volume = 255, audio-track = "player-sfx" }
exetior_stomp = { file = "Player/Exetior/exetior_stomp.wav", volume = 255, audio-track = "player-sfx" }
exetior_stompland = { file = "Player/Exetior/exetior_stompland.wav", volume = 255, audio-track = "player-sfx" }
exetior_stun = { file = "Player/Exetior/exetior_stun.wav", volume = 255, audio-track = "player-sfx" }
exetior_taunt1 = { file = "Player/Exetior/exetior_taunt1.wav", volume = 255, audio-track = "player-sfx" }
exetior_taunt2 = { file = "Player/Exetior/exetior_taunt2.wav", volume = 255, audio-track = "player-sfx" }
exetior_taunt3 = { file = "Player/Exetior/exetior_taunt3.wav", volume = 255, audio-track = "player-sfx" }
exewin = { file = "Music/exewin.mp3", volume = 255, audio-track = "music" }
expweak = { file = "Effects/expweak.wav", volume = 255, audio-track = "player-sfx" }
fart = { file = "fart.mp3", volume = 255, audio-track = "player-sfx" }
fartzone = { file = "Music/fartzone.ogg", volume = 77, audio-track = "music" }
fartzone_chase = { file = "Music/fartzone_chase.ogg", volume = 255, audio-track = "music" }
fnac = { file = "fnac.ogg", volume = 255, audio-track = "player-sfx" }
hauntdream = { file = "Music/hauntdream.mp3", volume = 178, audio-track = "music" }
hauntdream_chase = { file = "Music/hauntdream_chase.mp3", volume = 178, audio-track = "music" }
heal = { file = "Player/heal.wav", volume = 255, audio-track = "player-sfx" }
hideandseek2 = { file = "Music/hideandseek2.mp3", volume = 77, audio-track = "music" }
hideandseek2_chase = { file = "Music/hideandseek2_chase.mp3", volume = 77, audio-track = "music" }
hill = { file = "Music/hill.ogg", volume = 255, audio-track = "music" }
hill_chase = { file = "Music/hill_chase.mp3", volume = 255, audio-track = "music" }
hurt = { file = "Player/hurt.wav", volume = 255, audio-track = "player-sfx" }
ice_break = { file = "Objects/ice_break.wav", volume = 255, audio-track = "player-sfx" }
ice_spawn = { file = "Objects/ice_spawn.wav", volume = 255, audio-track = "player-sfx" }
judger = { file = "Objects/judger.wav", volume = 255, audio-track = "player-sfx" }
jump = { file = "Player/jump.wav", volume = 255, audio-track = "player-sfx" }
kindandfair = { file = "Music/kindandfair.mp3", volume = 77, audio-track = "music" }
kindandfair_chase = { file = "Music/kindandfair_chase.mp3", volume = 77, audio-track = "music" }
lava = { file = "Objects/lava.wav", volume = 255, audio-track = "player-sfx" }
lavaappear = { file = "Objects/lavaappear.wav", volume = 255, audio-track = "player-sfx" }
lavahit = { file = "Objects/lavahit.wav", volume = 255, audio-track = "player-sfx" }
level = { file = "Music/level.ogg", volume = 255, audio-track = "music" }
lift = { file = "Objects/lift.wav", volume = 255, audio-track = "player-sfx" }
limpcity = { file = "Music/limpcity.mp3", volume = 77, audio-track = "music" }
limpcity_chase = { file = "Music/limpcity_chase.mp3", volume = 77, audio-track = "music" }
lobby = { file = "Music/lobby.ogg", volume = 77, audio-track = "music" }
lobby_epic = { file = "Music/lobby_epic.ogg", volume = 77, audio-track = "music" }
logo = { file = "Music/logo.ogg", volume = 51, audio-track = "music" }
majinforest = { file = "Music/majinforest.mp3", volume = 77, audio-track = "music" }
majinforest_chase = { file = "Music/majinforest_chase.mp3", volume = 153, audio-track = "music" }
marijuna = { file = "Music/marijuna.mp3", volume = 128, audio-track = "music" }
marijuna_chase = { file = "Music/marijuna_chase.mp3", volume = 153, audio-track = "music" }
menu = { file = "Music/menu.ogg", volume = 51, audio-track = "music" }
menu_press = { file = "Menu/menu_press.wav", volume = 255, audio-track = "ui-sfx" }
menu_select = { file = "Menu/menu_select.wav", volume = 255, audio-track = "ui-sfx" }
mermer = { file = "mermer.wav", volume = 255, audio-track = "player-sfx" }
message = { file = "message.wav", volume = 255, audio-track = "ui-sfx" }
mindfuck = { file = "Music/mindfuck.mp3", volume = 77, audio-track = "music" }
minibal = { file = "Minigame/minibal.wav", volume = 255, audio-track = "player-sfx" }
minidestroy = { file = "Minigame/minidestroy.wav", volume = 255, audio-track = "player-sfx" }
minidie = { file = "Minigame/minidie.wav", volume = 255, audio-track = "player-sfx" }
miniextra = { file = "Minigame/miniextra.wav", volume = 255, audio-track = "player-sfx" }
minigame = { file = "Music/minigame.ogg", volume = 255, audio-track = "music" }
minispin = { file = "Minigame/minispin.wav", volume = 255, audio-track = "player-sfx" }
ministart = { file = "Minigame/ministart.wav", volume = 255, audio-track = "player-sfx" }
movingspike = { file = "Objects/movingspike.wav", volume = 191, audio-track = "player-sfx" }
nastyparadise = { file = "Music/nastyparadise.mp3", volume = 128, audio-track = "music" }
nastyparadise_chase = { file = "Music/nastyparadise_chase.mp3", volume = 77, audio-track = "music" }
none = { file = "none.wav", volume = 255, audio-track = "player-sfx" }
nono = { file = "Menu/nono.wav", volume = 255, audio-track = "ui-sfx" }
notperfect = { file = "Music/notperfect.ogg", volume = 77, audio-track = "music" }
notperfect_chase = { file = "Music/notperfect_chase.ogg", volume = 77, audio-track = "music" }
npteleport = { file = "npteleport.wav", volume = 255, audio-track = "player-sfx" }
pns = { file = "Effects/pns.ogg", volume = 255, audio-track = "player-sfx" }
pricelessfreedom = { file = "Music/pricelessfreedom.mp3", volume = 77, audio-track = "music" }
pricelessfreedom_chase = { file = "Music/pricelessfreedom_chase.mp3", volume = 77, audio-track = "music" }
rain = { file = "Ambient/rain.ogg", volume = 255, audio-track = "ambient" }
ravimemist = { file = "Music/ravimemist.mp3", volume = 77, audio-track = "music" }
ravimemist_chase = { file = "Music/ravimemist_chase.mp3", volume = 77, audio-track = "music" }
ready = { file = "Menu/ready.wav", volume = 255, audio-track = "ui-sfx" }
redring = { file = "Objects/redring.wav", volume = 255, audio-track = "player-sfx" }
ring = { file = "Objects/ring.wav", volume = 255, audio-track = "player-sfx" }
ringabsorb = { file = "Objects/ringabsorb.wav", volume = 255, audio-track = "player-sfx" }
ringlose = { file = "Objects/ringlose.wav", volume = 255, audio-track = "player-sfx" }
roar = { file = "Player/roar.mp3", volume = 255, audio-track = "player-sfx" }
sally_shield = { file = "Player/Sally/sally_shield.wav", volume = 255, audio-track = "player-sfx" }
sally_shieldbreak = { file = "Player/Sally/sally_shieldbreak.wav", volume = 255, audio-track = "player-sfx" }
sally_slide = { file = "Player/Sally/sally_slide.wav", volume = 255, audio-track = "player-sfx" }
shard = { file = "Objects/shard.wav", volume = 255, audio-track = "player-sfx" }
slime = { file = "Objects/slime.wav", volume = 255, audio-track = "player-sfx" }
smoke = { file = "Effects/smoke.ogg", volume = 255, audio-track = "player-sfx" }
snap = { file = "Player/Knuckles/snap.wav", volume = 255, audio-track = "player-sfx" }
snowball_break = { file = "Objects/snowball_break.wav", volume = 255, audio-track = "player-sfx" }
snowball_roll = { file = "Objects/snowball_roll.wav", volume = 255, audio-track = "player-sfx" }
spike = { file = "Objects/spike.wav", volume = 255, audio-track = "player-sfx" }
spin = { file = "Player/spin.wav", volume = 255, audio-track = "player-sfx" }
spring = { file = "Objects/spring.wav", volume = 255, audio-track = "player-sfx" }
spring_reverb = { file = "Objects/spring_reverb.ogg", volume = 255, audio-track = "player-sfx" }
stalactite_notice = { file = "Objects/stalactite_notice.wav", volume = 255, audio-track = "player-sfx" }
suddendeath = { file = "Ambient/suddendeath.mp3", volume = 255, audio-track = "ambient" }
survivor_win = { file = "Ambient/survivor_win.mp3", volume = 255, audio-track = "ambient" }
survwin = { file = "Music/survwin.mp3", volume = 255, audio-track = "music" }
tails_charge = { file = "Player/Tails/tails_charge.wav", volume = 255, audio-track = "player-sfx" }
tails_fly = { file = "Player/Tails/tails_fly.wav", volume = 255, audio-track = "player-sfx" }
tails_hit = { file = "Player/Tails/tails_hit.mp3", volume = 255, audio-track = "player-sfx" }
tails_shoot = { file = "Player/Tails/tails_shoot.wav", volume = 255, audio-track = "player-sfx" }
tailsball = { file = "Objects/tailsball.ogg", volume = 252, audio-track = "player-sfx" }
tailsball_chase = { file = "Objects/tailsball_chase.ogg", volume = 255, audio-track = "player-sfx" }
tailsball_jumpscare = { file = "Objects/tailsball_jumpscare.ogg", volume = 128, audio-track = "player-sfx" }
tailsball_jumpscare2 = { file = "Objects/tailsball_jumpscare2.wav", volume = 153, audio-track = "player-sfx" }
teleport = { file = "Player/teleport.wav", volume = 255, audio-track = "player-sfx" }
thunder = { file = "Ambient/thunder.mp3", volume = 255, audio-track = "ambient" }
timeover = { file = "Music/timeover.mp3", volume = 255, audio-track = "music" }
torturecave = { file = "Music/torturecave.ogg", volume = 102, audio-track = "music" }
torturecave_chase = { file = "Music/torturecave_chase.ogg", volume = 102, audio-track = "music" }
vasebreak = { file = "Objects/vasebreak.wav", volume = 255, audio-track = "player-sfx" }
volcanovalley = { file = "Music/volcanovalley.ogg", volume = 77, audio-track = "music" }
volcanovalley_chase = { file = "Music/volcanovalley_chase.mp3", volume = 77, audio-track = "music" }
waiting = { file = "Music/waiting.ogg", volume = 102, audio-track = "music" }
waterdrops = { file = "Ambient/waterdrops.wav", volume = 255, audio-track = "ambient" }
watersplash = { file = "Effects/watersplash.wav", volume = 255, audio-track = "player-sfx" }
wdarms = { file = "Objects/wdarms.mp3", volume = 173, audio-track = "player-sfx" }
wdlamp = { file = "Objects/wdlamp.mp3", volume = 102, audio-track = "player-sfx" }
weedzone = { file = "Music/weedzone.ogg", volume = 102, audio-track = "music" }
weedzone_chase = { file = "Music/weedzone_chase.mp3", volume = 102, audio-track = "music" }
youcantrun = { file = "Music/youcantrun.mp3", volume = 77, audio-track = "music" }
youcantrun_chase = { file = "Music/youcantrun_chase.ogg", volume = 77, audio-track = "music" }
