// Generated once by the converter from the GameMaker project, maintained by hand since.
#![allow(dead_code)]
//! Object types and their editor settings (sprite, parent, flags).

use crate::core::resources::names::sprite;
use crate::core::resources::SpriteId;

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum ObjectId {
    AbadonCloud,
    AbandonFace,
    AbandonMine,
    Abyss,
    AbyssTarget,
    Achivements,
    Act9Bodies,
    Act9Instakill,
    Act9Wall,
    AizBush,
    AizPalm,
    AizZipline,
    AizZiplineEnd,
    AizZiplineStart,
    AmCollision,
    AmController,
    AmHideobject,
    Amy,
    Angleallower,
    Angleanuller,
    AngleanullerEggsafe,
    Asteroid,
    AsteroidBreakable,
    AsteroidPart,
    Bigring,
    BigringTeleport,
    Blackfadein,
    Blackfadeout,
    Blackring,
    BlackringSpawner,
    BluespheresSphere,
    BspringLeft,
    BspringRight,
    BspringUp,
    Camera,
    Camerachecker,
    Chaos,
    ChaosLiquid,
    Config,
    Connecting,
    Controls,
    Corpse,
    CorpseAmy,
    CorpseCream,
    CorpseEggman,
    CorpseKnux,
    CorpseTails,
    Cream,
    Damage,
    DarktowerBall,
    DarktowerDarkness,
    DarktowerFog,
    DarktowerJumpscare,
    DarktowerLiquid,
    DarktowerStalactite,
    DarktowerStalactitePart,
    DarktowerTailsdoll,
    Deathtp,
    DeathtpPoint,
    DemonIndicator,
    Deserttown,
    DeserttownHide,
    DeserttownHide2,
    DeserttownI,
    DeserttownMisc,
    DeserttownTiles,
    DeserttownTrigger,
    DotdotdotI,
    DotdotdotShitladder,
    DotdotdotTrigger,
    DotdotdotTrigger2,
    DotdotdotTrigger3,
    Egg,
    Eggstatue,
    Eggtrack,
    Ending,
    Exe,
    ExeIndicator,
    ExeSprindicator,
    Exeller,
    ExellerClone,
    ExellerIndicator,
    ExellerIndicatorDown,
    ExellerIndicatorUp,
    Exespawn,
    Exetior,
    ExetiorIndicator,
    ExetiorStompballs,
    FartAss,
    FartController,
    FartDummy,
    FartMermer,
    FartText,
    FartTile,
    Flash,
    FloorParent,
    GhzController,
    GhzRain,
    GhzSlope,
    GhzSlope2,
    GhzSlope3,
    GhzSlope4,
    GhzSlope5,
    GhzWater,
    GhzWave,
    Granny,
    HdCollision,
    HdCrystal,
    HdDoor,
    HdDoor2,
    HdHide,
    HdSpring,
    HealParticle,
    HealProgress,
    HidingParent,
    Hn2Slope1,
    Hn2Slope2,
    JackInTheBox,
    KafSlope1,
    KafSlope2,
    KafSpeedbox,
    Knux,
    LeftPusher,
    Level,
    LimpcityEchain1,
    LimpcityEchain2,
    LimpcityEyea,
    LimpcityEyeb,
    LimpcityEyechain,
    LimpcityEyechain2,
    LimpcityHideeye,
    Lobby,
    LobbyBlood,
    LobbyFire,
    LobbyIcon,
    LobbyProlet,
    LobbyVotekick,
    LobbyWaiting,
    LobbyWhite,
    Logo,
    MajongController,
    MajongSlope,
    MajongSound,
    MajongTrigger,
    MajongTriggerPoint,
    MarijunaCrystal,
    MarijunaCrystalcontroller,
    MarijunaStatue,
    MarijunaJudger,
    MarijunaJudgerpor,
    MarijunaLavaplatform,
    MarijunaPlatform,
    MarijunaSlops,
    MarjiunaStatic,
    Menu,
    MenuAbouttext,
    MenuAchivements,
    MenuAchvarrow,
    MenuButton,
    MenuCharacter,
    MenuCharacters,
    MenuCredits,
    MenuExeempire,
    MenuGif,
    MenuIcon,
    MenuJoin,
    MenuLink1,
    MenuLink2,
    MenuMobilebutton,
    MenuMobilebutton2,
    MenuMobiledpad,
    MenuMoney,
    MenuWarning,
    MenuParticle,
    MenuParticlespawner,
    MenuPet,
    MenuSecret,
    MenuServerbutton,
    MenuSkin,
    MenuSlider,
    MenuText,
    MenuTextbox,
    MenuTextpanel,
    MenuTogglebutton,
    MenuVersion,
    MenuWaiting,
    MenuWaitkick,
    Message,
    Minigame,
    Minisnoc,
    MinisnocEggy,
    MinisnocEggy2,
    MinisnocFade,
    MinigameTrail,
    Movingspike,
    NapController,
    NapIceblock,
    NapIceblockPart,
    NapIcespike,
    NapSnow,
    NapSnowball,
    NapSnowballPart,
    NapSnowballWaypoint,
    NapTrigger,
    Netclient,
    NpBackground,
    NpController,
    NpTeleporn,
    NpWhite,
    Npring,
    Parallax,
    PetChao,
    PetDadol,
    PetEgg,
    PetFlicky,
    PetMajin,
    PetMetal,
    PetMknux,
    PetSecret,
    PfLift,
    PlatformJumptrough,
    PlayerPovodok,
    PlayerPuppet,
    PlayerSensoral,
    PlayerSensorar,
    PlayerSensorbl,
    PlayerSensorbr,
    PlayerSensorl,
    PlayerSensorr,
    PlayerSensortl,
    PlayerSensortr,
    PlayerWarning,
    Playerui,
    PuppetTail,
    Quickeffect,
    QuickeffectFade,
    RavinemistBush,
    RavinemistBushAnimated,
    RavinemistController,
    RavintmistShard,
    Redring,
    RedringScreen,
    RedringScreen2,
    Results,
    ResultsIcon,
    RevivalPuppet,
    RightPusher,
    Ring,
    RingSpawner,
    Ringpart,
    Ringspawn,
    Rmzsonic,
    Sally,
    Shadertest,
    SolidBlock,
    SolidBlock2,
    SolidParent,
    Soundemitter,
    Spawnpoint,
    Spike,
    SpikeR,
    SpringLeft,
    SpringParent,
    SpringRight,
    SpringUp,
    Suddendeath,
    SurvIndicator,
    SurvLampindicator,
    SurvRingindicator,
    Tails,
    TailsProjectile,
    TailsTail,
    Tile,
    Unlockables,
    VvBarrel,
    VvBarrel2,
    VvLavacolumn,
    VvVase,
    VvVasepiece,
    Warning,
    Weed,
    WeedConveyor,
    WeedConveyor2,
    WeedConveyor3,
    WeedGhost,
    WeedGhost2,
    WeedLantern,
    WeedLantern2,
    WeedLantern3,
    WeedLight,
    WeedSelfinsert,
    WeedSlope,
    WeedSlopeJumpthrough,
    WeedZone,
    YcrSlope,
    YcrSlope2,
    YcrSmoke,
    YcrSmokearea,
    YspringUp,
}

pub struct ObjectInfo {
    pub name: &'static str,
    pub sprite: Option<SpriteId>,
    pub mask: Option<SpriteId>,
    pub parent: Option<ObjectId>,
    pub visible: bool,
    pub persistent: bool,
    pub solid: bool,
}

pub const ALL_OBJECTS: [ObjectId; 299] = [
    ObjectId::AbadonCloud,
    ObjectId::AbandonFace,
    ObjectId::AbandonMine,
    ObjectId::Abyss,
    ObjectId::AbyssTarget,
    ObjectId::Achivements,
    ObjectId::Act9Bodies,
    ObjectId::Act9Instakill,
    ObjectId::Act9Wall,
    ObjectId::AizBush,
    ObjectId::AizPalm,
    ObjectId::AizZipline,
    ObjectId::AizZiplineEnd,
    ObjectId::AizZiplineStart,
    ObjectId::AmCollision,
    ObjectId::AmController,
    ObjectId::AmHideobject,
    ObjectId::Amy,
    ObjectId::Angleallower,
    ObjectId::Angleanuller,
    ObjectId::AngleanullerEggsafe,
    ObjectId::Asteroid,
    ObjectId::AsteroidBreakable,
    ObjectId::AsteroidPart,
    ObjectId::Bigring,
    ObjectId::BigringTeleport,
    ObjectId::Blackfadein,
    ObjectId::Blackfadeout,
    ObjectId::Blackring,
    ObjectId::BlackringSpawner,
    ObjectId::BluespheresSphere,
    ObjectId::BspringLeft,
    ObjectId::BspringRight,
    ObjectId::BspringUp,
    ObjectId::Camera,
    ObjectId::Camerachecker,
    ObjectId::Chaos,
    ObjectId::ChaosLiquid,
    ObjectId::Config,
    ObjectId::Connecting,
    ObjectId::Controls,
    ObjectId::Corpse,
    ObjectId::CorpseAmy,
    ObjectId::CorpseCream,
    ObjectId::CorpseEggman,
    ObjectId::CorpseKnux,
    ObjectId::CorpseTails,
    ObjectId::Cream,
    ObjectId::Damage,
    ObjectId::DarktowerBall,
    ObjectId::DarktowerDarkness,
    ObjectId::DarktowerFog,
    ObjectId::DarktowerJumpscare,
    ObjectId::DarktowerLiquid,
    ObjectId::DarktowerStalactite,
    ObjectId::DarktowerStalactitePart,
    ObjectId::DarktowerTailsdoll,
    ObjectId::Deathtp,
    ObjectId::DeathtpPoint,
    ObjectId::DemonIndicator,
    ObjectId::Deserttown,
    ObjectId::DeserttownHide,
    ObjectId::DeserttownHide2,
    ObjectId::DeserttownI,
    ObjectId::DeserttownMisc,
    ObjectId::DeserttownTiles,
    ObjectId::DeserttownTrigger,
    ObjectId::DotdotdotI,
    ObjectId::DotdotdotShitladder,
    ObjectId::DotdotdotTrigger,
    ObjectId::DotdotdotTrigger2,
    ObjectId::DotdotdotTrigger3,
    ObjectId::Egg,
    ObjectId::Eggstatue,
    ObjectId::Eggtrack,
    ObjectId::Ending,
    ObjectId::Exe,
    ObjectId::ExeIndicator,
    ObjectId::ExeSprindicator,
    ObjectId::Exeller,
    ObjectId::ExellerClone,
    ObjectId::ExellerIndicator,
    ObjectId::ExellerIndicatorDown,
    ObjectId::ExellerIndicatorUp,
    ObjectId::Exespawn,
    ObjectId::Exetior,
    ObjectId::ExetiorIndicator,
    ObjectId::ExetiorStompballs,
    ObjectId::FartAss,
    ObjectId::FartController,
    ObjectId::FartDummy,
    ObjectId::FartMermer,
    ObjectId::FartText,
    ObjectId::FartTile,
    ObjectId::Flash,
    ObjectId::FloorParent,
    ObjectId::GhzController,
    ObjectId::GhzRain,
    ObjectId::GhzSlope,
    ObjectId::GhzSlope2,
    ObjectId::GhzSlope3,
    ObjectId::GhzSlope4,
    ObjectId::GhzSlope5,
    ObjectId::GhzWater,
    ObjectId::GhzWave,
    ObjectId::Granny,
    ObjectId::HdCollision,
    ObjectId::HdCrystal,
    ObjectId::HdDoor,
    ObjectId::HdDoor2,
    ObjectId::HdHide,
    ObjectId::HdSpring,
    ObjectId::HealParticle,
    ObjectId::HealProgress,
    ObjectId::HidingParent,
    ObjectId::Hn2Slope1,
    ObjectId::Hn2Slope2,
    ObjectId::JackInTheBox,
    ObjectId::KafSlope1,
    ObjectId::KafSlope2,
    ObjectId::KafSpeedbox,
    ObjectId::Knux,
    ObjectId::LeftPusher,
    ObjectId::Level,
    ObjectId::LimpcityEchain1,
    ObjectId::LimpcityEchain2,
    ObjectId::LimpcityEyea,
    ObjectId::LimpcityEyeb,
    ObjectId::LimpcityEyechain,
    ObjectId::LimpcityEyechain2,
    ObjectId::LimpcityHideeye,
    ObjectId::Lobby,
    ObjectId::LobbyBlood,
    ObjectId::LobbyFire,
    ObjectId::LobbyIcon,
    ObjectId::LobbyProlet,
    ObjectId::LobbyVotekick,
    ObjectId::LobbyWaiting,
    ObjectId::LobbyWhite,
    ObjectId::Logo,
    ObjectId::MajongController,
    ObjectId::MajongSlope,
    ObjectId::MajongSound,
    ObjectId::MajongTrigger,
    ObjectId::MajongTriggerPoint,
    ObjectId::MarijunaCrystal,
    ObjectId::MarijunaCrystalcontroller,
    ObjectId::MarijunaStatue,
    ObjectId::MarijunaJudger,
    ObjectId::MarijunaJudgerpor,
    ObjectId::MarijunaLavaplatform,
    ObjectId::MarijunaPlatform,
    ObjectId::MarijunaSlops,
    ObjectId::MarjiunaStatic,
    ObjectId::Menu,
    ObjectId::MenuAbouttext,
    ObjectId::MenuAchivements,
    ObjectId::MenuAchvarrow,
    ObjectId::MenuButton,
    ObjectId::MenuCharacter,
    ObjectId::MenuCharacters,
    ObjectId::MenuCredits,
    ObjectId::MenuExeempire,
    ObjectId::MenuGif,
    ObjectId::MenuIcon,
    ObjectId::MenuJoin,
    ObjectId::MenuLink1,
    ObjectId::MenuLink2,
    ObjectId::MenuMobilebutton,
    ObjectId::MenuMobilebutton2,
    ObjectId::MenuMobiledpad,
    ObjectId::MenuMoney,
    ObjectId::MenuWarning,
    ObjectId::MenuParticle,
    ObjectId::MenuParticlespawner,
    ObjectId::MenuPet,
    ObjectId::MenuSecret,
    ObjectId::MenuServerbutton,
    ObjectId::MenuSkin,
    ObjectId::MenuSlider,
    ObjectId::MenuText,
    ObjectId::MenuTextbox,
    ObjectId::MenuTextpanel,
    ObjectId::MenuTogglebutton,
    ObjectId::MenuVersion,
    ObjectId::MenuWaiting,
    ObjectId::MenuWaitkick,
    ObjectId::Message,
    ObjectId::Minigame,
    ObjectId::Minisnoc,
    ObjectId::MinisnocEggy,
    ObjectId::MinisnocEggy2,
    ObjectId::MinisnocFade,
    ObjectId::MinigameTrail,
    ObjectId::Movingspike,
    ObjectId::NapController,
    ObjectId::NapIceblock,
    ObjectId::NapIceblockPart,
    ObjectId::NapIcespike,
    ObjectId::NapSnow,
    ObjectId::NapSnowball,
    ObjectId::NapSnowballPart,
    ObjectId::NapSnowballWaypoint,
    ObjectId::NapTrigger,
    ObjectId::Netclient,
    ObjectId::NpBackground,
    ObjectId::NpController,
    ObjectId::NpTeleporn,
    ObjectId::NpWhite,
    ObjectId::Npring,
    ObjectId::Parallax,
    ObjectId::PetChao,
    ObjectId::PetDadol,
    ObjectId::PetEgg,
    ObjectId::PetFlicky,
    ObjectId::PetMajin,
    ObjectId::PetMetal,
    ObjectId::PetMknux,
    ObjectId::PetSecret,
    ObjectId::PfLift,
    ObjectId::PlatformJumptrough,
    ObjectId::PlayerPovodok,
    ObjectId::PlayerPuppet,
    ObjectId::PlayerSensoral,
    ObjectId::PlayerSensorar,
    ObjectId::PlayerSensorbl,
    ObjectId::PlayerSensorbr,
    ObjectId::PlayerSensorl,
    ObjectId::PlayerSensorr,
    ObjectId::PlayerSensortl,
    ObjectId::PlayerSensortr,
    ObjectId::PlayerWarning,
    ObjectId::Playerui,
    ObjectId::PuppetTail,
    ObjectId::Quickeffect,
    ObjectId::QuickeffectFade,
    ObjectId::RavinemistBush,
    ObjectId::RavinemistBushAnimated,
    ObjectId::RavinemistController,
    ObjectId::RavintmistShard,
    ObjectId::Redring,
    ObjectId::RedringScreen,
    ObjectId::RedringScreen2,
    ObjectId::Results,
    ObjectId::ResultsIcon,
    ObjectId::RevivalPuppet,
    ObjectId::RightPusher,
    ObjectId::Ring,
    ObjectId::RingSpawner,
    ObjectId::Ringpart,
    ObjectId::Ringspawn,
    ObjectId::Rmzsonic,
    ObjectId::Sally,
    ObjectId::Shadertest,
    ObjectId::SolidBlock,
    ObjectId::SolidBlock2,
    ObjectId::SolidParent,
    ObjectId::Soundemitter,
    ObjectId::Spawnpoint,
    ObjectId::Spike,
    ObjectId::SpikeR,
    ObjectId::SpringLeft,
    ObjectId::SpringParent,
    ObjectId::SpringRight,
    ObjectId::SpringUp,
    ObjectId::Suddendeath,
    ObjectId::SurvIndicator,
    ObjectId::SurvLampindicator,
    ObjectId::SurvRingindicator,
    ObjectId::Tails,
    ObjectId::TailsProjectile,
    ObjectId::TailsTail,
    ObjectId::Tile,
    ObjectId::Unlockables,
    ObjectId::VvBarrel,
    ObjectId::VvBarrel2,
    ObjectId::VvLavacolumn,
    ObjectId::VvVase,
    ObjectId::VvVasepiece,
    ObjectId::Warning,
    ObjectId::Weed,
    ObjectId::WeedConveyor,
    ObjectId::WeedConveyor2,
    ObjectId::WeedConveyor3,
    ObjectId::WeedGhost,
    ObjectId::WeedGhost2,
    ObjectId::WeedLantern,
    ObjectId::WeedLantern2,
    ObjectId::WeedLantern3,
    ObjectId::WeedLight,
    ObjectId::WeedSelfinsert,
    ObjectId::WeedSlope,
    ObjectId::WeedSlopeJumpthrough,
    ObjectId::WeedZone,
    ObjectId::YcrSlope,
    ObjectId::YcrSlope2,
    ObjectId::YcrSmoke,
    ObjectId::YcrSmokearea,
    ObjectId::YspringUp,
];

impl ObjectId {
    pub fn info(self) -> ObjectInfo {
        match self {
            ObjectId::AbadonCloud => ObjectInfo { name: "obj_abadon_cloud", sprite: Some(sprite::SPR_AM_CLOUD), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::AbandonFace => ObjectInfo { name: "obj_abandon_face", sprite: Some(sprite::SPR_AM_FACE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::AbandonMine => ObjectInfo { name: "obj_abandon_mine", sprite: Some(sprite::SPR_AM_OOH), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Abyss => ObjectInfo { name: "obj_abyss", sprite: Some(sprite::SPR_ABYSS), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::AbyssTarget => ObjectInfo { name: "obj_abyss_target", sprite: Some(sprite::SPR_ABYSS_TARGET), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Achivements => ObjectInfo { name: "obj_achivements", sprite: None, mask: None, parent: None, visible: true, persistent: true, solid: false },
            ObjectId::Act9Bodies => ObjectInfo { name: "obj_act9_bodies", sprite: Some(sprite::SPR_ACT9_DEAD), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Act9Instakill => ObjectInfo { name: "obj_act9_instakill", sprite: Some(sprite::SPR_RED), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Act9Wall => ObjectInfo { name: "obj_act9_wall", sprite: Some(sprite::SPR_ACT9_WALL), mask: None, parent: Some(ObjectId::SolidBlock), visible: true, persistent: false, solid: false },
            ObjectId::AizBush => ObjectInfo { name: "obj_aiz_bush", sprite: Some(sprite::SPR_AIZ_DECOR2), mask: None, parent: Some(ObjectId::HidingParent), visible: true, persistent: false, solid: false },
            ObjectId::AizPalm => ObjectInfo { name: "obj_aiz_palm", sprite: Some(sprite::SPR_AIZ_DECOR), mask: None, parent: Some(ObjectId::HidingParent), visible: true, persistent: false, solid: false },
            ObjectId::AizZipline => ObjectInfo { name: "obj_aiz_zipline", sprite: Some(sprite::SPR_AIZ_ZIPLINE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::AizZiplineEnd => ObjectInfo { name: "obj_aiz_zipline_end", sprite: Some(sprite::SPR_AIZ_ZIPLINE), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::AizZiplineStart => ObjectInfo { name: "obj_aiz_zipline_start", sprite: Some(sprite::SPR_AIZ_ZIPLINE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::AmCollision => ObjectInfo { name: "obj_am_collision", sprite: Some(sprite::SPR_AM_COLLISION), mask: None, parent: Some(ObjectId::SolidParent), visible: true, persistent: false, solid: false },
            ObjectId::AmController => ObjectInfo { name: "obj_am_controller", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::AmHideobject => ObjectInfo { name: "obj_am_hideobject", sprite: Some(sprite::SPR_GREEN293), mask: None, parent: Some(ObjectId::HidingParent), visible: false, persistent: false, solid: false },
            ObjectId::Amy => ObjectInfo { name: "obj_amy", sprite: Some(sprite::SPR_AMY_IDLE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Angleallower => ObjectInfo { name: "obj_angleallower", sprite: Some(sprite::SPR_RED), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Angleanuller => ObjectInfo { name: "obj_angleanuller", sprite: Some(sprite::SPR_RAMPHELPER_RIGHT), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::AngleanullerEggsafe => ObjectInfo { name: "obj_angleanuller_eggsafe", sprite: Some(sprite::SPR_RAMPHELPER_RIGHT), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Asteroid => ObjectInfo { name: "obj_asteroid", sprite: Some(sprite::SPR_SOTA2), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::AsteroidBreakable => ObjectInfo { name: "obj_asteroid_breakable", sprite: Some(sprite::SPR_SOTA), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::AsteroidPart => ObjectInfo { name: "obj_asteroid_part", sprite: Some(sprite::SPR_SOTA3), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Bigring => ObjectInfo { name: "obj_bigring", sprite: Some(sprite::SPR_BIGRING), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::BigringTeleport => ObjectInfo { name: "obj_bigring_teleport", sprite: Some(sprite::SPR_RING_TELEPORT), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Blackfadein => ObjectInfo { name: "obj_blackfadein", sprite: Some(sprite::SPR_BLACK), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Blackfadeout => ObjectInfo { name: "obj_blackfadeout", sprite: Some(sprite::SPR_BLACK), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Blackring => ObjectInfo { name: "obj_blackring", sprite: Some(sprite::SPR_BLACKRING), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::BlackringSpawner => ObjectInfo { name: "obj_blackring_spawner", sprite: Some(sprite::SPR_BLACKRING), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::BluespheresSphere => ObjectInfo { name: "obj_bluespheres_sphere", sprite: Some(sprite::SPR_BLUESHPERES_SPHERE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::BspringLeft => ObjectInfo { name: "obj_bspring_left", sprite: Some(sprite::SPR_BSPRING_LEFT), mask: None, parent: Some(ObjectId::SpringUp), visible: true, persistent: false, solid: false },
            ObjectId::BspringRight => ObjectInfo { name: "obj_bspring_right", sprite: Some(sprite::SPR_BSPRING_RIGHT), mask: None, parent: Some(ObjectId::SpringUp), visible: true, persistent: false, solid: false },
            ObjectId::BspringUp => ObjectInfo { name: "obj_bspring_up", sprite: Some(sprite::SPR_BSPRING_UP), mask: None, parent: Some(ObjectId::SpringParent), visible: true, persistent: false, solid: false },
            ObjectId::Camera => ObjectInfo { name: "obj_camera", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Camerachecker => ObjectInfo { name: "obj_camerachecker", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Chaos => ObjectInfo { name: "obj_chaos", sprite: Some(sprite::SPR_CHAOS_EMOTION1), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::ChaosLiquid => ObjectInfo { name: "obj_chaos_liquid", sprite: Some(sprite::SPR_CHAOS_LIQUID), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Config => ObjectInfo { name: "obj_config", sprite: None, mask: None, parent: None, visible: true, persistent: true, solid: false },
            ObjectId::Connecting => ObjectInfo { name: "obj_connecting", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Controls => ObjectInfo { name: "obj_controls", sprite: None, mask: None, parent: None, visible: true, persistent: true, solid: false },
            ObjectId::Corpse => ObjectInfo { name: "obj_corpse", sprite: None, mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::CorpseAmy => ObjectInfo { name: "obj_corpse_amy", sprite: Some(sprite::SPR_CORPSE_AMY), mask: None, parent: Some(ObjectId::Corpse), visible: false, persistent: false, solid: false },
            ObjectId::CorpseCream => ObjectInfo { name: "obj_corpse_cream", sprite: Some(sprite::SPR_CORPSE_CREAM), mask: None, parent: Some(ObjectId::Corpse), visible: false, persistent: false, solid: false },
            ObjectId::CorpseEggman => ObjectInfo { name: "obj_corpse_eggman", sprite: Some(sprite::SPR_CORPSE_EGGMAN), mask: None, parent: Some(ObjectId::Corpse), visible: false, persistent: false, solid: false },
            ObjectId::CorpseKnux => ObjectInfo { name: "obj_corpse_knux", sprite: Some(sprite::SPR_CORPSE_KNUX), mask: None, parent: Some(ObjectId::Corpse), visible: false, persistent: false, solid: false },
            ObjectId::CorpseTails => ObjectInfo { name: "obj_corpse_tails", sprite: Some(sprite::SPR_CORPSE_TAILS), mask: None, parent: Some(ObjectId::Corpse), visible: false, persistent: false, solid: false },
            ObjectId::Cream => ObjectInfo { name: "obj_cream", sprite: Some(sprite::SPR_CREAM_FALL), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Damage => ObjectInfo { name: "obj_damage", sprite: Some(sprite::SPR_RED), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::DarktowerBall => ObjectInfo { name: "obj_darktower_ball", sprite: Some(sprite::SPR_DARKTOWER_BALL), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::DarktowerDarkness => ObjectInfo { name: "obj_darktower_darkness", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::DarktowerFog => ObjectInfo { name: "obj_darktower_fog", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::DarktowerJumpscare => ObjectInfo { name: "obj_darktower_jumpscare", sprite: None, mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::DarktowerLiquid => ObjectInfo { name: "obj_darktower_liquid", sprite: Some(sprite::SPR_DARKTOWER_STALACTITE1), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::DarktowerStalactite => ObjectInfo { name: "obj_darktower_stalactite", sprite: Some(sprite::SPR_DARKTOWER_STALACTITE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::DarktowerStalactitePart => ObjectInfo { name: "obj_darktower_stalactitepart", sprite: Some(sprite::SPR_DARKTOWER_STALACTITE2), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::DarktowerTailsdoll => ObjectInfo { name: "obj_darktower_tailsdoll", sprite: Some(sprite::SPR_DARKTOWER_TAILSOL), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Deathtp => ObjectInfo { name: "obj_deathtp", sprite: Some(sprite::SPR_DEATHTP), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::DeathtpPoint => ObjectInfo { name: "obj_deathtp_point", sprite: Some(sprite::SPR_DEATHTP_POINT), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::DemonIndicator => ObjectInfo { name: "obj_demon_indicator", sprite: Some(sprite::SPR_INDICATOR2), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Deserttown => ObjectInfo { name: "obj_deserttown", sprite: Some(sprite::SPR_DESERTTOWN_TILES), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::DeserttownHide => ObjectInfo { name: "obj_deserttown_hide", sprite: Some(sprite::SPR_DESERTTOWN_HIDE), mask: None, parent: Some(ObjectId::HidingParent), visible: true, persistent: false, solid: false },
            ObjectId::DeserttownHide2 => ObjectInfo { name: "obj_deserttown_hide2", sprite: Some(sprite::SPR_DESERTTOWN_HIDE2), mask: None, parent: Some(ObjectId::HidingParent), visible: true, persistent: false, solid: false },
            ObjectId::DeserttownI => ObjectInfo { name: "obj_deserttown_i", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::DeserttownMisc => ObjectInfo { name: "obj_deserttown_misc", sprite: Some(sprite::SPR_DESERTTOWN_MISC), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::DeserttownTiles => ObjectInfo { name: "obj_deserttown_tiles", sprite: Some(sprite::SPR_DESERTTOWN_MISCTILES), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::DeserttownTrigger => ObjectInfo { name: "obj_deserttown_trigger", sprite: Some(sprite::SPR_GREEN), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::DotdotdotI => ObjectInfo { name: "obj_dotdotdot_i", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::DotdotdotShitladder => ObjectInfo { name: "obj_dotdotdot_shitladder", sprite: Some(sprite::SPR_MERFURMU2), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::DotdotdotTrigger => ObjectInfo { name: "obj_dotdotdot_trigger", sprite: Some(sprite::SPR_GREEN), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::DotdotdotTrigger2 => ObjectInfo { name: "obj_dotdotdot_trigger2", sprite: Some(sprite::SPR_ABYSS), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::DotdotdotTrigger3 => ObjectInfo { name: "obj_dotdotdot_trigger3", sprite: Some(sprite::SPR_GREEN), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Egg => ObjectInfo { name: "obj_egg", sprite: Some(sprite::SPR_EGG_IDLE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Eggstatue => ObjectInfo { name: "obj_eggstatue", sprite: Some(sprite::SPR_DOT_EGGSTATUE), mask: None, parent: Some(ObjectId::HidingParent), visible: true, persistent: false, solid: false },
            ObjectId::Eggtrack => ObjectInfo { name: "obj_eggtrack", sprite: Some(sprite::SPR_EGGTRACK), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Ending => ObjectInfo { name: "obj_ending", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Exe => ObjectInfo { name: "obj_exe", sprite: Some(sprite::SPR_EXE_IDLE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::ExeIndicator => ObjectInfo { name: "obj_exe_indicator", sprite: Some(sprite::SPR_INDICATOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::ExeSprindicator => ObjectInfo { name: "obj_exe_sprindicator", sprite: Some(sprite::SPR_INDICATOR3), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Exeller => ObjectInfo { name: "obj_exeller", sprite: Some(sprite::SPR_EXELLER_CLONE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::ExellerClone => ObjectInfo { name: "obj_exeller_clone", sprite: Some(sprite::SPR_EXELLER_CLONE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::ExellerIndicator => ObjectInfo { name: "obj_exeller_indicator", sprite: Some(sprite::SPR_INDICATOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::ExellerIndicatorDown => ObjectInfo { name: "obj_exeller_indicator_down", sprite: Some(sprite::SPR_EXELLER_CLONETRACKER2), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::ExellerIndicatorUp => ObjectInfo { name: "obj_exeller_indicator_up", sprite: Some(sprite::SPR_EXELLER_CLONETRACKER), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Exespawn => ObjectInfo { name: "obj_exespawn", sprite: Some(sprite::SPR_EXESPAWN), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Exetior => ObjectInfo { name: "obj_exetior", sprite: Some(sprite::SPR_EXETIOR_LOST), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::ExetiorIndicator => ObjectInfo { name: "obj_exetior_indicator", sprite: Some(sprite::SPR_INDICATOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::ExetiorStompballs => ObjectInfo { name: "obj_exetior_stompballs", sprite: Some(sprite::SPR_EXETIOR_STOMPBALLS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::FartAss => ObjectInfo { name: "obj_fart_ass", sprite: Some(sprite::SPR_BOOM), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::FartController => ObjectInfo { name: "obj_fart_controller", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::FartDummy => ObjectInfo { name: "obj_fart_dummy", sprite: Some(sprite::SPR_FART_DUMMY), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::FartMermer => ObjectInfo { name: "obj_fart_mermer", sprite: Some(sprite::SPR_MERFURMU), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::FartText => ObjectInfo { name: "obj_fart_text", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::FartTile => ObjectInfo { name: "obj_fart_tile", sprite: Some(sprite::SPR_FARTZONE), mask: None, parent: Some(ObjectId::FloorParent), visible: true, persistent: false, solid: false },
            ObjectId::Flash => ObjectInfo { name: "obj_flash", sprite: Some(sprite::SPR_WHITE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::FloorParent => ObjectInfo { name: "obj_floor_parent", sprite: None, mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::GhzController => ObjectInfo { name: "obj_ghz_controller", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::GhzRain => ObjectInfo { name: "obj_ghz_rain", sprite: Some(sprite::SPR_GHZ_RAIN), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::GhzSlope => ObjectInfo { name: "obj_ghz_slope", sprite: Some(sprite::SPR_GHZ_SLOPE1), mask: None, parent: Some(ObjectId::PlatformJumptrough), visible: true, persistent: false, solid: false },
            ObjectId::GhzSlope2 => ObjectInfo { name: "obj_ghz_slope2", sprite: Some(sprite::SPR_GHZ_SLOPE2), mask: None, parent: Some(ObjectId::SolidBlock), visible: true, persistent: false, solid: false },
            ObjectId::GhzSlope3 => ObjectInfo { name: "obj_ghz_slope3", sprite: Some(sprite::SPR_GHZ_SLOPE3), mask: None, parent: Some(ObjectId::SolidBlock), visible: true, persistent: false, solid: false },
            ObjectId::GhzSlope4 => ObjectInfo { name: "obj_ghz_slope4", sprite: Some(sprite::SPR_GHZ_SLOPE4), mask: None, parent: Some(ObjectId::PlatformJumptrough), visible: true, persistent: false, solid: false },
            ObjectId::GhzSlope5 => ObjectInfo { name: "obj_ghz_slope5", sprite: Some(sprite::SPR_GHZ_SLOPE5), mask: None, parent: Some(ObjectId::PlatformJumptrough), visible: true, persistent: false, solid: false },
            ObjectId::GhzWater => ObjectInfo { name: "obj_ghz_water", sprite: Some(sprite::SPR_GREEN), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::GhzWave => ObjectInfo { name: "obj_ghz_wave", sprite: Some(sprite::SPR_GHZ_WAVE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Granny => ObjectInfo { name: "obj_granny", sprite: Some(sprite::SPR_MINISNOC_EXTRA), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::HdCollision => ObjectInfo { name: "obj_hd_collision", sprite: Some(sprite::SPD_HD_COLLIISON), mask: None, parent: Some(ObjectId::SolidBlock), visible: true, persistent: false, solid: false },
            ObjectId::HdCrystal => ObjectInfo { name: "obj_hd_crystal", sprite: Some(sprite::SPR_HD_CRYSTAL), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::HdDoor => ObjectInfo { name: "obj_hd_door", sprite: Some(sprite::SPR_HD_DOOR), mask: None, parent: Some(ObjectId::FloorParent), visible: true, persistent: false, solid: false },
            ObjectId::HdDoor2 => ObjectInfo { name: "obj_hd_door2", sprite: Some(sprite::SPR_HD_DOOR2), mask: None, parent: Some(ObjectId::FloorParent), visible: true, persistent: false, solid: false },
            ObjectId::HdHide => ObjectInfo { name: "obj_hd_hide", sprite: Some(sprite::SPR_HD_HIDE), mask: None, parent: Some(ObjectId::HidingParent), visible: true, persistent: false, solid: false },
            ObjectId::HdSpring => ObjectInfo { name: "obj_hd_spring", sprite: Some(sprite::SPR_HD_SPRING), mask: Some(sprite::SPR_HD_SPRING), parent: None, visible: true, persistent: false, solid: false },
            ObjectId::HealParticle => ObjectInfo { name: "obj_heal_particle", sprite: Some(sprite::SPR_HEAL_PART), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::HealProgress => ObjectInfo { name: "obj_heal_progress", sprite: Some(sprite::SPR_HEAL), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::HidingParent => ObjectInfo { name: "obj_hiding_parent", sprite: None, mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::Hn2Slope1 => ObjectInfo { name: "obj_hn2_slope1", sprite: Some(sprite::SPR_HS2_SLOPE1), mask: None, parent: Some(ObjectId::SolidParent), visible: true, persistent: false, solid: false },
            ObjectId::Hn2Slope2 => ObjectInfo { name: "obj_hn2_slope2", sprite: Some(sprite::SPR_HS2_SLOPE2), mask: None, parent: Some(ObjectId::SolidParent), visible: true, persistent: false, solid: false },
            ObjectId::JackInTheBox => ObjectInfo { name: "obj_jack_in_the_box", sprite: Some(sprite::SPR_HS2_BOX), mask: None, parent: Some(ObjectId::HidingParent), visible: true, persistent: false, solid: false },
            ObjectId::KafSlope1 => ObjectInfo { name: "obj_kaf_slope1", sprite: Some(sprite::SPR_KINDNFAIR_SLOPE1), mask: None, parent: Some(ObjectId::SolidBlock), visible: false, persistent: false, solid: false },
            ObjectId::KafSlope2 => ObjectInfo { name: "obj_kaf_slope2", sprite: Some(sprite::SPR_KINDNFAIR_SLOPE2), mask: None, parent: Some(ObjectId::SolidBlock), visible: false, persistent: false, solid: false },
            ObjectId::KafSpeedbox => ObjectInfo { name: "obj_kaf_speedbox", sprite: Some(sprite::SPR_KINDNFAIR_SPEEDBOX), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Knux => ObjectInfo { name: "obj_knux", sprite: Some(sprite::SPR_KNUX_IDLE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::LeftPusher => ObjectInfo { name: "obj_left_pusher", sprite: Some(sprite::SPR_RED), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Level => ObjectInfo { name: "obj_level", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::LimpcityEchain1 => ObjectInfo { name: "obj_limpcity_echain1", sprite: Some(sprite::SPR_LIMPCITY_CHAIN1), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::LimpcityEchain2 => ObjectInfo { name: "obj_limpcity_echain2", sprite: Some(sprite::SPR_LIMPCITY_CHAIN2), mask: None, parent: Some(ObjectId::LimpcityEchain1), visible: true, persistent: false, solid: false },
            ObjectId::LimpcityEyea => ObjectInfo { name: "obj_limpcity_eyeA", sprite: Some(sprite::SPR_LIMPCITY_EYE_RECHARGE), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::LimpcityEyeb => ObjectInfo { name: "obj_limpcity_eyeB", sprite: Some(sprite::SPR_LIMPCITY_EYE_RECHARGE), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::LimpcityEyechain => ObjectInfo { name: "obj_limpcity_eyechain", sprite: Some(sprite::SPR_LIMPCITY_EYE_CHAIN), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::LimpcityEyechain2 => ObjectInfo { name: "obj_limpcity_eyechain2", sprite: Some(sprite::SPR_LIMPCITY_EYE_CHAIN), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::LimpcityHideeye => ObjectInfo { name: "obj_limpcity_hideeye", sprite: Some(sprite::SPR_LIMPCITY_HIDEEYE), mask: None, parent: Some(ObjectId::HidingParent), visible: true, persistent: false, solid: false },
            ObjectId::Lobby => ObjectInfo { name: "obj_lobby", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::LobbyBlood => ObjectInfo { name: "obj_lobby_blood", sprite: Some(sprite::SPR_BLOOD2), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::LobbyFire => ObjectInfo { name: "obj_lobby_fire", sprite: None, mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::LobbyIcon => ObjectInfo { name: "obj_lobby_icon", sprite: Some(sprite::SPR_LOBBY_ICON), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::LobbyProlet => ObjectInfo { name: "obj_lobby_prolet", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::LobbyVotekick => ObjectInfo { name: "obj_lobby_votekick", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::LobbyWaiting => ObjectInfo { name: "obj_lobby_waiting", sprite: Some(sprite::SPR_LOBBY_WAITING), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::LobbyWhite => ObjectInfo { name: "obj_lobby_white", sprite: Some(sprite::SPR_WHITE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Logo => ObjectInfo { name: "obj_logo", sprite: Some(sprite::SPR_LOGO_LOGOS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MajongController => ObjectInfo { name: "obj_majong_controller", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MajongSlope => ObjectInfo { name: "obj_majong_slope", sprite: Some(sprite::SPR_MAJONG_SLOPE), mask: None, parent: Some(ObjectId::FloorParent), visible: false, persistent: false, solid: false },
            ObjectId::MajongSound => ObjectInfo { name: "obj_majong_sound", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MajongTrigger => ObjectInfo { name: "obj_majong_trigger", sprite: Some(sprite::SPR_RED), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::MajongTriggerPoint => ObjectInfo { name: "obj_majong_trigger_point", sprite: Some(sprite::SPR_DEATHTP_POINT), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::MarijunaCrystal => ObjectInfo { name: "obj_marijuna_crystal", sprite: Some(sprite::SPR_MARIJUNA_CRYSTAL), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MarijunaCrystalcontroller => ObjectInfo { name: "obj_marijuna_crystalcontroller", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MarijunaStatue => ObjectInfo { name: "obj_marijuna_statue", sprite: Some(sprite::SPR_MARIJUNA_STATUE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MarijunaJudger => ObjectInfo { name: "obj_marijuna_judger", sprite: Some(sprite::SPR_MARIJUNA_JUDGER), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MarijunaJudgerpor => ObjectInfo { name: "obj_marijuna_judgerpor", sprite: Some(sprite::SPR_MARIJUNA_FIREBALL), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MarijunaLavaplatform => ObjectInfo { name: "obj_marijuna_lavaplatform", sprite: Some(sprite::SPR_MARIJUNA_LAVAPLATFORM), mask: None, parent: Some(ObjectId::PlatformJumptrough), visible: true, persistent: false, solid: false },
            ObjectId::MarijunaPlatform => ObjectInfo { name: "obj_marijuna_platform", sprite: Some(sprite::SPR_GREEN293), mask: None, parent: Some(ObjectId::SolidBlock), visible: true, persistent: false, solid: false },
            ObjectId::MarijunaSlops => ObjectInfo { name: "obj_marijuna_slops", sprite: Some(sprite::SPR_MARIJUNA_SLOPES), mask: None, parent: Some(ObjectId::SolidParent), visible: true, persistent: false, solid: false },
            ObjectId::MarjiunaStatic => ObjectInfo { name: "obj_marjiuna_static", sprite: Some(sprite::SPR_STATIC), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Menu => ObjectInfo { name: "obj_menu", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuAbouttext => ObjectInfo { name: "obj_menu_abouttext", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuAchivements => ObjectInfo { name: "obj_menu_achivements", sprite: Some(sprite::SPR_ACHIVEMENTS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuAchvarrow => ObjectInfo { name: "obj_menu_achvarrow", sprite: Some(sprite::SPR_ACHIVARROWS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuButton => ObjectInfo { name: "obj_menu_button", sprite: Some(sprite::SPR_MENU_BUTTONS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuCharacter => ObjectInfo { name: "obj_menu_character", sprite: Some(sprite::SPR_MENU_EGG), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuCharacters => ObjectInfo { name: "obj_menu_characters", sprite: Some(sprite::SPR_MENU_CHARACTERS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuCredits => ObjectInfo { name: "obj_menu_credits", sprite: Some(sprite::SPR_MENU_CREDITS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuExeempire => ObjectInfo { name: "obj_menu_exeempire", sprite: Some(sprite::SPR_MENU_LINKS2), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuGif => ObjectInfo { name: "obj_menu_gif", sprite: Some(sprite::SPR_MENU_SPIN), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuIcon => ObjectInfo { name: "obj_menu_icon", sprite: Some(sprite::SPR_MENU_ICON), mask: None, parent: Some(ObjectId::MenuButton), visible: true, persistent: false, solid: false },
            ObjectId::MenuJoin => ObjectInfo { name: "obj_menu_join", sprite: Some(sprite::SPR_MENU_BUTTONS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuLink1 => ObjectInfo { name: "obj_menu_link1", sprite: Some(sprite::SPR_MENU_LINKS2), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuLink2 => ObjectInfo { name: "obj_menu_link2", sprite: Some(sprite::SPR_MENU_LINKS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuMobilebutton => ObjectInfo { name: "obj_menu_mobilebutton", sprite: Some(sprite::SPR_MOBILE_BUTTON), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuMobilebutton2 => ObjectInfo { name: "obj_menu_mobilebutton2", sprite: Some(sprite::SPR_MOBILE_EMOTIONBUTTON), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuMobiledpad => ObjectInfo { name: "obj_menu_mobiledpad", sprite: Some(sprite::SPR_MOBILE_DPAD), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuMoney => ObjectInfo { name: "obj_menu_money", sprite: Some(sprite::SPR_COUNTER), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuWarning => ObjectInfo { name: "obj_menu_warning", sprite: Some(sprite::SPR_MENU_WARNING), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuParticle => ObjectInfo { name: "obj_menu_particle", sprite: Some(sprite::SPR_MENU_PARTICLE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuParticlespawner => ObjectInfo { name: "obj_menu_particlespawner", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuPet => ObjectInfo { name: "obj_menu_pet", sprite: Some(sprite::SPR_MENU_ICON), mask: None, parent: Some(ObjectId::MenuButton), visible: true, persistent: false, solid: false },
            ObjectId::MenuSecret => ObjectInfo { name: "obj_menu_secret", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuServerbutton => ObjectInfo { name: "obj_menu_serverbutton", sprite: Some(sprite::SPR_MENU_PUBLIC), mask: None, parent: Some(ObjectId::MenuButton), visible: true, persistent: false, solid: false },
            ObjectId::MenuSkin => ObjectInfo { name: "obj_menu_skin", sprite: Some(sprite::SPR_MENU_SKIN), mask: None, parent: Some(ObjectId::MenuButton), visible: true, persistent: false, solid: false },
            ObjectId::MenuSlider => ObjectInfo { name: "obj_menu_slider", sprite: Some(sprite::SPR_MENU_SLIDER), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuText => ObjectInfo { name: "obj_menu_text", sprite: Some(sprite::SPR_MENU_BUTTONS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuTextbox => ObjectInfo { name: "obj_menu_textbox", sprite: Some(sprite::SPR_MENU_TEXTBOX), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuTextpanel => ObjectInfo { name: "obj_menu_textpanel", sprite: Some(sprite::SPR_MENU_TEXTPANEL), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuTogglebutton => ObjectInfo { name: "obj_menu_togglebutton", sprite: Some(sprite::SPR_MENU_BUTTONS), mask: None, parent: Some(ObjectId::MenuButton), visible: true, persistent: false, solid: false },
            ObjectId::MenuVersion => ObjectInfo { name: "obj_menu_version", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuWaiting => ObjectInfo { name: "obj_menu_waiting", sprite: Some(sprite::SPR_MENU_WAITING), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MenuWaitkick => ObjectInfo { name: "obj_menu_waitkick", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Message => ObjectInfo { name: "obj_message", sprite: Some(sprite::SPR_MENU_ERROR), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Minigame => ObjectInfo { name: "obj_minigame", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Minisnoc => ObjectInfo { name: "obj_minisnoc", sprite: Some(sprite::SPR_MINISNOC), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MinisnocEggy => ObjectInfo { name: "obj_minisnoc_eggy", sprite: Some(sprite::SPR_MINISNOC_GRAVEYARD), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MinisnocEggy2 => ObjectInfo { name: "obj_minisnoc_eggy2", sprite: Some(sprite::SPR_MINISNOC_MCBIGTASTY), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MinisnocFade => ObjectInfo { name: "obj_minisnoc_fade", sprite: Some(sprite::SPR_SOTA), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::MinigameTrail => ObjectInfo { name: "obj_minigame_trail", sprite: Some(sprite::SPR_DUST), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Movingspike => ObjectInfo { name: "obj_movingspike", sprite: Some(sprite::SPR_SPIKE_MOVING), mask: None, parent: Some(ObjectId::SolidParent), visible: true, persistent: false, solid: false },
            ObjectId::NapController => ObjectInfo { name: "obj_nap_controller", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::NapIceblock => ObjectInfo { name: "obj_nap_iceblock", sprite: Some(sprite::SPR_NAP_ICEBLOCK), mask: None, parent: Some(ObjectId::FloorParent), visible: true, persistent: false, solid: false },
            ObjectId::NapIceblockPart => ObjectInfo { name: "obj_nap_iceblock_part", sprite: Some(sprite::SPR_NAP_ICEBLOCK_PART), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::NapIcespike => ObjectInfo { name: "obj_nap_icespike", sprite: Some(sprite::SPR_NAP_ICESPIKE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::NapSnow => ObjectInfo { name: "obj_nap_snow", sprite: Some(sprite::SPR_NAP_SNOW), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::NapSnowball => ObjectInfo { name: "obj_nap_snowball", sprite: Some(sprite::SPR_NAP_SNOWBALL), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::NapSnowballPart => ObjectInfo { name: "obj_nap_snowball_part", sprite: Some(sprite::SPR_NAP_SNOWBALL_PART), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::NapSnowballWaypoint => ObjectInfo { name: "obj_nap_snowball_waypoint", sprite: Some(sprite::SPR_SNBWAY), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::NapTrigger => ObjectInfo { name: "obj_nap_trigger", sprite: Some(sprite::SPR_RED), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Netclient => ObjectInfo { name: "obj_netclient", sprite: None, mask: None, parent: None, visible: true, persistent: true, solid: false },
            ObjectId::NpBackground => ObjectInfo { name: "obj_np_background", sprite: Some(sprite::BACKGROUND_NOTPERF), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::NpController => ObjectInfo { name: "obj_np_controller", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::NpTeleporn => ObjectInfo { name: "obj_np_teleporn", sprite: Some(sprite::SPR_RED), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::NpWhite => ObjectInfo { name: "obj_np_white", sprite: Some(sprite::SPR_WHITE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Npring => ObjectInfo { name: "obj_npring", sprite: Some(sprite::SPR_BIGRING), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Parallax => ObjectInfo { name: "obj_parallax", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PetChao => ObjectInfo { name: "obj_pet_chao", sprite: Some(sprite::SPR_PET_CHAO), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PetDadol => ObjectInfo { name: "obj_pet_dadol", sprite: Some(sprite::SPR_PET_DALDOL), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PetEgg => ObjectInfo { name: "obj_pet_egg", sprite: Some(sprite::SPR_PET_EGG), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PetFlicky => ObjectInfo { name: "obj_pet_flicky", sprite: Some(sprite::SPR_PET_FLICKY), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PetMajin => ObjectInfo { name: "obj_pet_majin", sprite: Some(sprite::SPR_PET_MAJIN), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PetMetal => ObjectInfo { name: "obj_pet_metal", sprite: Some(sprite::SPR_PET_METAL), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PetMknux => ObjectInfo { name: "obj_pet_mknux", sprite: Some(sprite::SPR_PET_MKNUX), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PetSecret => ObjectInfo { name: "obj_pet_secret", sprite: Some(sprite::SPR_PET_TITS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PfLift => ObjectInfo { name: "obj_pf_lift", sprite: Some(sprite::SPR_PF_LIFT), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PlatformJumptrough => ObjectInfo { name: "obj_platform_jumptrough", sprite: Some(sprite::SPR_PLATFORM), mask: None, parent: Some(ObjectId::FloorParent), visible: false, persistent: false, solid: false },
            ObjectId::PlayerPovodok => ObjectInfo { name: "obj_player_POVODOK", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PlayerPuppet => ObjectInfo { name: "obj_player_puppet", sprite: Some(sprite::SPR_MERFURMU), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PlayerSensoral => ObjectInfo { name: "obj_player_sensorAL", sprite: Some(sprite::SPR_SENSOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::PlayerSensorar => ObjectInfo { name: "obj_player_sensorAR", sprite: Some(sprite::SPR_SENSOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::PlayerSensorbl => ObjectInfo { name: "obj_player_sensorBL", sprite: Some(sprite::SPR_SENSOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::PlayerSensorbr => ObjectInfo { name: "obj_player_sensorBR", sprite: Some(sprite::SPR_SENSOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::PlayerSensorl => ObjectInfo { name: "obj_player_sensorL", sprite: Some(sprite::SPR_SENSOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::PlayerSensorr => ObjectInfo { name: "obj_player_sensorR", sprite: Some(sprite::SPR_SENSOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::PlayerSensortl => ObjectInfo { name: "obj_player_sensorTL", sprite: Some(sprite::SPR_SENSOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::PlayerSensortr => ObjectInfo { name: "obj_player_sensorTR", sprite: Some(sprite::SPR_SENSOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::PlayerWarning => ObjectInfo { name: "obj_player_warning", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Playerui => ObjectInfo { name: "obj_playerui", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::PuppetTail => ObjectInfo { name: "obj_puppet_tail", sprite: Some(sprite::SPR_TAILS_TAIL2), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Quickeffect => ObjectInfo { name: "obj_quickeffect", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::QuickeffectFade => ObjectInfo { name: "obj_quickeffect_fade", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::RavinemistBush => ObjectInfo { name: "obj_ravinemist_bush", sprite: Some(sprite::SPR_RAVINEMIST_BUSH), mask: None, parent: Some(ObjectId::HidingParent), visible: true, persistent: false, solid: false },
            ObjectId::RavinemistBushAnimated => ObjectInfo { name: "obj_ravinemist_bush_animated", sprite: Some(sprite::SPR_RAVINEMIST_BUSH_ANIMATED), mask: None, parent: Some(ObjectId::HidingParent), visible: true, persistent: false, solid: false },
            ObjectId::RavinemistController => ObjectInfo { name: "obj_ravinemist_controller", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::RavintmistShard => ObjectInfo { name: "obj_ravintmist_shard", sprite: Some(sprite::SPR_RAVINEMIST_SHARD), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Redring => ObjectInfo { name: "obj_redring", sprite: Some(sprite::SPR_REDRING), mask: None, parent: Some(ObjectId::Ring), visible: true, persistent: false, solid: false },
            ObjectId::RedringScreen => ObjectInfo { name: "obj_redring_screen", sprite: Some(sprite::SPR_REDRING_FORE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::RedringScreen2 => ObjectInfo { name: "obj_redring_screen2", sprite: Some(sprite::SPR_REDRING_FORE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Results => ObjectInfo { name: "obj_results", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::ResultsIcon => ObjectInfo { name: "obj_results_icon", sprite: Some(sprite::SPR_RESULTS_ICONS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::RevivalPuppet => ObjectInfo { name: "obj_revival_puppet", sprite: Some(sprite::SPR_REVIVAL), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::RightPusher => ObjectInfo { name: "obj_right_pusher", sprite: Some(sprite::SPR_RED), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Ring => ObjectInfo { name: "obj_ring", sprite: Some(sprite::SPR_RING), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::RingSpawner => ObjectInfo { name: "obj_ring_spawner", sprite: Some(sprite::SPR_RING), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Ringpart => ObjectInfo { name: "obj_ringpart", sprite: Some(sprite::SPR_RINGPART), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Ringspawn => ObjectInfo { name: "obj_ringspawn", sprite: Some(sprite::SPR_RINGSPAWN), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Rmzsonic => ObjectInfo { name: "obj_rmzsonic", sprite: Some(sprite::SPR_RAVINEMIST_SONIC), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Sally => ObjectInfo { name: "obj_sally", sprite: Some(sprite::SPR_SALLY_IDLE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Shadertest => ObjectInfo { name: "obj_shadertest", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::SolidBlock => ObjectInfo { name: "obj_solid_block", sprite: Some(sprite::SPR_BLOCK), mask: None, parent: Some(ObjectId::SolidParent), visible: false, persistent: false, solid: false },
            ObjectId::SolidBlock2 => ObjectInfo { name: "obj_solid_block2", sprite: Some(sprite::SPR_BLOCK2), mask: None, parent: Some(ObjectId::SolidBlock), visible: false, persistent: false, solid: false },
            ObjectId::SolidParent => ObjectInfo { name: "obj_solid_parent", sprite: None, mask: None, parent: Some(ObjectId::FloorParent), visible: false, persistent: false, solid: false },
            ObjectId::Soundemitter => ObjectInfo { name: "obj_soundemitter", sprite: Some(sprite::SPR_SOUNDEMITTER), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Spawnpoint => ObjectInfo { name: "obj_spawnpoint", sprite: Some(sprite::SPR_SPAWNPOINT), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Spike => ObjectInfo { name: "obj_spike", sprite: Some(sprite::SPR_SPIKE), mask: None, parent: Some(ObjectId::SolidParent), visible: true, persistent: false, solid: false },
            ObjectId::SpikeR => ObjectInfo { name: "obj_spike_r", sprite: Some(sprite::SPR_SPIKE_R), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::SpringLeft => ObjectInfo { name: "obj_spring_left", sprite: Some(sprite::SPR_SPRING_LEFT), mask: None, parent: Some(ObjectId::SpringUp), visible: true, persistent: false, solid: false },
            ObjectId::SpringParent => ObjectInfo { name: "obj_spring_parent", sprite: None, mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::SpringRight => ObjectInfo { name: "obj_spring_right", sprite: Some(sprite::SPR_SPRING_RIGHT), mask: None, parent: Some(ObjectId::SpringUp), visible: true, persistent: false, solid: false },
            ObjectId::SpringUp => ObjectInfo { name: "obj_spring_up", sprite: Some(sprite::SPR_SPRING_UP), mask: None, parent: Some(ObjectId::SpringParent), visible: true, persistent: false, solid: false },
            ObjectId::Suddendeath => ObjectInfo { name: "obj_suddendeath", sprite: Some(sprite::SPR_SUDDEN_DEATH), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::SurvIndicator => ObjectInfo { name: "obj_surv_indicator", sprite: Some(sprite::SPR_SINDICATOR), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::SurvLampindicator => ObjectInfo { name: "obj_surv_lampindicator", sprite: Some(sprite::SPR_SINDICATOR3), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::SurvRingindicator => ObjectInfo { name: "obj_surv_ringindicator", sprite: Some(sprite::SPR_SINDICATOR2), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Tails => ObjectInfo { name: "obj_tails", sprite: Some(sprite::SPR_TAILS_IDLE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::TailsProjectile => ObjectInfo { name: "obj_tails_projectile", sprite: Some(sprite::SPR_TAILS_RAY), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::TailsTail => ObjectInfo { name: "obj_tails_tail", sprite: Some(sprite::SPR_TAILS_TAIL2), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Tile => ObjectInfo { name: "obj_tile", sprite: Some(sprite::SPR_GREEN293), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::Unlockables => ObjectInfo { name: "obj_unlockables", sprite: None, mask: None, parent: None, visible: true, persistent: true, solid: false },
            ObjectId::VvBarrel => ObjectInfo { name: "obj_vv_barrel", sprite: Some(sprite::SPR_VV_BARREL), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::VvBarrel2 => ObjectInfo { name: "obj_vv_barrel2", sprite: Some(sprite::SPR_VV_BARREL2), mask: None, parent: Some(ObjectId::Camerachecker), visible: true, persistent: false, solid: false },
            ObjectId::VvLavacolumn => ObjectInfo { name: "obj_vv_lavacolumn", sprite: Some(sprite::SPR_VV_LAVACOLUMN), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::VvVase => ObjectInfo { name: "obj_vv_vase", sprite: Some(sprite::SPR_VV_VASE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::VvVasepiece => ObjectInfo { name: "obj_vv_vasepiece", sprite: Some(sprite::SPR_VV_VASEPIECE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Warning => ObjectInfo { name: "obj_warning", sprite: Some(sprite::SPR_WARNING), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::Weed => ObjectInfo { name: "obj_weed", sprite: None, mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::WeedConveyor => ObjectInfo { name: "obj_weed_conveyor", sprite: Some(sprite::SPR_WEED_CONVEYOR), mask: None, parent: Some(ObjectId::SolidParent), visible: true, persistent: false, solid: false },
            ObjectId::WeedConveyor2 => ObjectInfo { name: "obj_weed_conveyor2", sprite: Some(sprite::SPR_WEED_CONVEYOR2), mask: None, parent: Some(ObjectId::WeedConveyor), visible: true, persistent: false, solid: false },
            ObjectId::WeedConveyor3 => ObjectInfo { name: "obj_weed_conveyor3", sprite: Some(sprite::SPR_WEED_CONVEYOR3), mask: None, parent: Some(ObjectId::WeedConveyor), visible: true, persistent: false, solid: false },
            ObjectId::WeedGhost => ObjectInfo { name: "obj_weed_ghost", sprite: Some(sprite::SPR_WEED_GHOSTS), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::WeedGhost2 => ObjectInfo { name: "obj_weed_ghost2", sprite: Some(sprite::SPR_WEED_GHOSTS2), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::WeedLantern => ObjectInfo { name: "obj_weed_lantern", sprite: Some(sprite::SPR_WEED_LATERN), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::WeedLantern2 => ObjectInfo { name: "obj_weed_lantern2", sprite: Some(sprite::SPR_WEED_CHAIN), mask: None, parent: Some(ObjectId::WeedLantern), visible: true, persistent: false, solid: false },
            ObjectId::WeedLantern3 => ObjectInfo { name: "obj_weed_lantern3", sprite: Some(sprite::SPR_WEED_CHAIN2), mask: None, parent: Some(ObjectId::WeedLantern), visible: true, persistent: false, solid: false },
            ObjectId::WeedLight => ObjectInfo { name: "obj_weed_light", sprite: Some(sprite::SPR_WEED_LIGHT), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::WeedSelfinsert => ObjectInfo { name: "obj_weed_selfinsert", sprite: Some(sprite::SPR_SELFINSERT), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::WeedSlope => ObjectInfo { name: "obj_weed_slope", sprite: Some(sprite::SPR_WEED_SLOPE), mask: None, parent: Some(ObjectId::SolidBlock), visible: false, persistent: false, solid: false },
            ObjectId::WeedSlopeJumpthrough => ObjectInfo { name: "obj_weed_slope_jumpthrough", sprite: Some(sprite::SPR_WEED_SLOPE_JUMPTHROUGH), mask: None, parent: Some(ObjectId::PlatformJumptrough), visible: true, persistent: false, solid: false },
            ObjectId::WeedZone => ObjectInfo { name: "obj_weed_zone", sprite: Some(sprite::SPR_RED), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::YcrSlope => ObjectInfo { name: "obj_ycr_slope", sprite: Some(sprite::SPR_YCR_SLOPE), mask: None, parent: Some(ObjectId::PlatformJumptrough), visible: false, persistent: false, solid: false },
            ObjectId::YcrSlope2 => ObjectInfo { name: "obj_ycr_slope2", sprite: Some(sprite::SPR_YCR_SLOPE2), mask: None, parent: Some(ObjectId::PlatformJumptrough), visible: false, persistent: false, solid: false },
            ObjectId::YcrSmoke => ObjectInfo { name: "obj_ycr_smoke", sprite: Some(sprite::SPR_SMOKE), mask: None, parent: None, visible: true, persistent: false, solid: false },
            ObjectId::YcrSmokearea => ObjectInfo { name: "obj_ycr_smokearea", sprite: Some(sprite::SPR_RED), mask: None, parent: None, visible: false, persistent: false, solid: false },
            ObjectId::YspringUp => ObjectInfo { name: "obj_yspring_up", sprite: Some(sprite::SPR_YSPRING_UP), mask: None, parent: Some(ObjectId::SpringParent), visible: true, persistent: false, solid: false },
        }
    }
}
