// Generated once by the converter from the GameMaker project, maintained by hand since.
#![allow(dead_code)]
//! Rooms in the order of the GameMaker room list (the first one starts the game).
//! Each room's layout is the Tiled map Maps/<file>.tmj.

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum RoomId {
    Logo,
    Shadertest,
    Menu,
    Lobby,
    Ravinemist,
    Hideandseek2,
    Dotdotdot,
    Deserttown,
    Youcantrun,
    Limpcity,
    Fartzone,
    Kindandfair,
    Act9,
    Nastyparadise,
    Pricelessfreedom,
    Volcanovalley,
    Greenhill,
    Majongforest,
    Angelisland,
    Torturecave,
    Notperfect,
    Message,
    Connecting,
    Dartower,
    Haundream,
    Waiting,
    Results,
    Weedzone,
    Marijuna,
}

pub const ROOM_ORDER: [RoomId; 29] = [
    RoomId::Logo,
    RoomId::Shadertest,
    RoomId::Menu,
    RoomId::Lobby,
    RoomId::Ravinemist,
    RoomId::Hideandseek2,
    RoomId::Dotdotdot,
    RoomId::Deserttown,
    RoomId::Youcantrun,
    RoomId::Limpcity,
    RoomId::Fartzone,
    RoomId::Kindandfair,
    RoomId::Act9,
    RoomId::Nastyparadise,
    RoomId::Pricelessfreedom,
    RoomId::Volcanovalley,
    RoomId::Greenhill,
    RoomId::Majongforest,
    RoomId::Angelisland,
    RoomId::Torturecave,
    RoomId::Notperfect,
    RoomId::Message,
    RoomId::Connecting,
    RoomId::Dartower,
    RoomId::Haundream,
    RoomId::Waiting,
    RoomId::Results,
    RoomId::Weedzone,
    RoomId::Marijuna,
];

impl RoomId {
    /// Map file name inside Maps/, without extension.
    pub fn file_name(self) -> &'static str {
        match self {
            RoomId::Logo => "logo",
            RoomId::Shadertest => "shadertest",
            RoomId::Menu => "menu",
            RoomId::Lobby => "lobby",
            RoomId::Ravinemist => "ravinemist",
            RoomId::Hideandseek2 => "hideandseek2",
            RoomId::Dotdotdot => "dotdotdot",
            RoomId::Deserttown => "deserttown",
            RoomId::Youcantrun => "youcantrun",
            RoomId::Limpcity => "limpcity",
            RoomId::Fartzone => "fartzone",
            RoomId::Kindandfair => "kindandfair",
            RoomId::Act9 => "act9",
            RoomId::Nastyparadise => "nastyparadise",
            RoomId::Pricelessfreedom => "pricelessfreedom",
            RoomId::Volcanovalley => "volcanovalley",
            RoomId::Greenhill => "greenhill",
            RoomId::Majongforest => "majongforest",
            RoomId::Angelisland => "angelisland",
            RoomId::Torturecave => "torturecave",
            RoomId::Notperfect => "notperfect",
            RoomId::Message => "message",
            RoomId::Connecting => "connecting",
            RoomId::Dartower => "dartower",
            RoomId::Haundream => "haundream",
            RoomId::Waiting => "waiting",
            RoomId::Results => "results",
            RoomId::Weedzone => "weedzone",
            RoomId::Marijuna => "marijuna",
        }
    }

    pub fn gm_name(self) -> &'static str {
        match self {
            RoomId::Logo => "room_logo",
            RoomId::Shadertest => "room_shadertest",
            RoomId::Menu => "room_menu",
            RoomId::Lobby => "room_lobby",
            RoomId::Ravinemist => "room_ravinemist",
            RoomId::Hideandseek2 => "room_hideandseek2",
            RoomId::Dotdotdot => "room_dotdotdot",
            RoomId::Deserttown => "room_deserttown",
            RoomId::Youcantrun => "room_youcantrun",
            RoomId::Limpcity => "room_limpcity",
            RoomId::Fartzone => "room_fartzone",
            RoomId::Kindandfair => "room_kindandfair",
            RoomId::Act9 => "room_act9",
            RoomId::Nastyparadise => "room_nastyparadise",
            RoomId::Pricelessfreedom => "room_pricelessfreedom",
            RoomId::Volcanovalley => "room_volcanovalley",
            RoomId::Greenhill => "room_greenhill",
            RoomId::Majongforest => "room_majongforest",
            RoomId::Angelisland => "room_angelisland",
            RoomId::Torturecave => "room_torturecave",
            RoomId::Notperfect => "room_notperfect",
            RoomId::Message => "room_message",
            RoomId::Connecting => "room_connecting",
            RoomId::Dartower => "room_dartower",
            RoomId::Haundream => "room_haundream",
            RoomId::Waiting => "room_waiting",
            RoomId::Results => "room_results",
            RoomId::Weedzone => "room_weedzone",
            RoomId::Marijuna => "room_marijuna",
        }
    }
}
